<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Data and data handling (IES Week 5) – IES Statistical Practicals</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/07-descriptive.html" rel="next">
<link href="../chapters/04-prep1.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3294577322a5a8aac4f27c9836f2d0c7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/05-prep2.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data handling (IES Week 5)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">IES Statistical Practicals</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-prep1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R and R Studio (IES Week 4)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-prep2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data handling (IES Week 5)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing and visualising data (IES Week 7)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimation, precision, and study size (IES Week 8)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-comparison.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis tests and measures of association (IES Week 9)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression (IES Week 10)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-adjustment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear and logistic regression (IES Week 11)</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-intended-learning-outcomes" id="toc-chapter-intended-learning-outcomes" class="nav-link active" data-scroll-target="#chapter-intended-learning-outcomes"><span class="header-section-number">2.1</span> Chapter intended learning outcomes</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">2.2</span> Setup</a></li>
  <li><a href="#tidy-data-in-a-spreadsheet" id="toc-tidy-data-in-a-spreadsheet" class="nav-link" data-scroll-target="#tidy-data-in-a-spreadsheet"><span class="header-section-number">2.3</span> Tidy data, in a spreadsheet</a>
  <ul class="collapse">
  <li><a href="#what-makes-data-usable" id="toc-what-makes-data-usable" class="nav-link" data-scroll-target="#what-makes-data-usable"><span class="header-section-number">2.3.1</span> What makes data usable</a></li>
  <li><a href="#what-breaks-an-import" id="toc-what-breaks-an-import" class="nav-link" data-scroll-target="#what-breaks-an-import"><span class="header-section-number">2.3.2</span> What breaks an import</a></li>
  </ul></li>
  <li><a href="#finding-a-file-and-telling-r-where-it-is" id="toc-finding-a-file-and-telling-r-where-it-is" class="nav-link" data-scroll-target="#finding-a-file-and-telling-r-where-it-is"><span class="header-section-number">2.4</span> Finding a file, and telling R where it is</a></li>
  <li><a href="#getting-data-in" id="toc-getting-data-in" class="nav-link" data-scroll-target="#getting-data-in"><span class="header-section-number">2.5</span> Getting data in</a>
  <ul class="collapse">
  <li><a href="#read_csv-and-here" id="toc-read_csv-and-here" class="nav-link" data-scroll-target="#read_csv-and-here"><span class="header-section-number">2.5.1</span> <code>read_csv()</code> and <code>here()</code></a></li>
  <li><a href="#four-things-that-go-wrong" id="toc-four-things-that-go-wrong" class="nav-link" data-scroll-target="#four-things-that-go-wrong"><span class="header-section-number">2.5.2</span> Four things that go wrong</a></li>
  <li><a href="#the-block-of-output-youll-see" id="toc-the-block-of-output-youll-see" class="nav-link" data-scroll-target="#the-block-of-output-youll-see"><span class="header-section-number">2.5.3</span> The block of output you’ll see</a></li>
  <li><a href="#a-first-look" id="toc-a-first-look" class="nav-link" data-scroll-target="#a-first-look"><span class="header-section-number">2.5.4</span> A first look</a></li>
  <li><a href="#when-r-guesses-the-wrong-type" id="toc-when-r-guesses-the-wrong-type" class="nav-link" data-scroll-target="#when-r-guesses-the-wrong-type"><span class="header-section-number">2.5.5</span> When R guesses the wrong type</a></li>
  <li><a href="#spotting-missing-data" id="toc-spotting-missing-data" class="nav-link" data-scroll-target="#spotting-missing-data"><span class="header-section-number">2.5.6</span> Spotting missing data</a></li>
  <li><a href="#using-the-dictionary-file" id="toc-using-the-dictionary-file" class="nav-link" data-scroll-target="#using-the-dictionary-file"><span class="header-section-number">2.5.7</span> Using the dictionary file</a></li>
  </ul></li>
  <li><a href="#a-first-analysis-and-your-first-script" id="toc-a-first-analysis-and-your-first-script" class="nav-link" data-scroll-target="#a-first-analysis-and-your-first-script"><span class="header-section-number">2.6</span> A first analysis, and your first script</a>
  <ul class="collapse">
  <li><a href="#one-summary-statistic" id="toc-one-summary-statistic" class="nav-link" data-scroll-target="#one-summary-statistic"><span class="header-section-number">2.6.1</span> One summary statistic</a></li>
  <li><a href="#a-first-taste-of-a-grouped-summary" id="toc-a-first-taste-of-a-grouped-summary" class="nav-link" data-scroll-target="#a-first-taste-of-a-grouped-summary"><span class="header-section-number">2.6.2</span> A first taste of a grouped summary</a></li>
  <li><a href="#a-first-taste-of-a-plot" id="toc-a-first-taste-of-a-plot" class="nav-link" data-scroll-target="#a-first-taste-of-a-plot"><span class="header-section-number">2.6.3</span> A first taste of a plot</a></li>
  <li><a href="#that-warning-above-the-plot" id="toc-that-warning-above-the-plot" class="nav-link" data-scroll-target="#that-warning-above-the-plot"><span class="header-section-number">2.6.4</span> That warning above the plot</a></li>
  <li><a href="#from-console-to-script" id="toc-from-console-to-script" class="nav-link" data-scroll-target="#from-console-to-script"><span class="header-section-number">2.6.5</span> From console to script</a></li>
  <li><a href="#proving-it-actually-works" id="toc-proving-it-actually-works" class="nav-link" data-scroll-target="#proving-it-actually-works"><span class="header-section-number">2.6.6</span> Proving it actually works</a></li>
  <li><a href="#how-this-book-is-put-together" id="toc-how-this-book-is-put-together" class="nav-link" data-scroll-target="#how-this-book-is-put-together"><span class="header-section-number">2.6.7</span> How this book is put together</a></li>
  </ul></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">2.7</span> Exercises</a></li>
  <li><a href="#self-check" id="toc-self-check" class="nav-link" data-scroll-target="#self-check"><span class="header-section-number">2.8</span> Self-check</a></li>
  <li><a href="#writing-exercise" id="toc-writing-exercise" class="nav-link" data-scroll-target="#writing-exercise"><span class="header-section-number">2.9</span> Writing exercise</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-05-prep2" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data handling (IES Week 5)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This session follows IES Week 4, where we learned the language itself: objects, functions, packages, and how to read an error message. Today we bring in real data for the first time. We’ll take a spreadsheet apart to see what makes it usable, import it into R, look it over, spot what’s missing, and produce one small piece of real analysis, start to finish. By the end you will have written and saved your own R script, and re-run it from a fresh session to prove it still works. That is the way you’ll work for the rest of the course. IES Week 6 is reading week, so there’s no practical for it, and IES Week 7 picks up from here and goes straight into using <code>nhanes_mph</code> properly.</p>
<section id="chapter-intended-learning-outcomes" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="chapter-intended-learning-outcomes"><span class="header-section-number">2.1</span> Chapter intended learning outcomes</h2>
<p>By the end of this session you will be able to:</p>
<ol type="1">
<li>Identify features of a spreadsheet that will prevent it being analysed, and restructure it</li>
<li>Import a CSV into R using a correctly specified path, and diagnose and resolve the most common import failures</li>
<li>Inspect an imported dataset’s dimensions, variable names, types, and missing values</li>
<li>Write, save, and re-run an R script that imports data, summarises it, and produces a plot</li>
<li>Locate a downloaded file on your own operating system, construct or copy a valid path to it, and explain what a CSV file physically contains</li>
</ol>
</section>
<section id="setup" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="setup"><span class="header-section-number">2.2</span> Setup</h2>
<p>There’s nothing to read in yet, so, as in IES Week 4, this chunk only sets the console’s print width.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">width =</span> <span class="dv">76</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="tidy-data-in-a-spreadsheet" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="tidy-data-in-a-spreadsheet"><span class="header-section-number">2.3</span> Tidy data, in a spreadsheet</h2>
<section id="what-makes-data-usable" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="what-makes-data-usable"><span class="header-section-number">2.3.1</span> What makes data usable</h3>
<p>A dataset R can work with follows three simple rules: one variable per column, one observation per row, one value per cell. Data laid out this way is called <strong>tidy</strong>. It sounds obvious written down, but very few spreadsheets people actually hand you follow it, because a spreadsheet is usually built to be <em>read by a person</em>, not imported by software. People merge cells to make a heading look nice. They use colour instead of writing a word down. They leave blank rows for visual spacing. None of that survives import, and some of it actively breaks it.</p>
</section>
<section id="what-breaks-an-import" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="what-breaks-an-import"><span class="header-section-number">2.3.2</span> What breaks an import</h3>
<ul>
<li><strong>Merged cells.</strong> A heading merged across several columns looks fine to a person, but when R reads the underlying columns back out, most of them come back empty, because the merge only stored the value in one of the cells it covers.</li>
<li><strong>Colour used to carry information</strong>, instead of a word or a number. A whole row filled in, say, yellow to mean “smoker”, with no column recording it at all, and the only place that tells you what the colour means is a caption sitting several rows away, disconnected from the table itself. R reads cell values, not cell fills, so the colour disappears completely on import, and the caption comes in as an isolated row of text with nothing left to connect it back to the patients it was describing.</li>
<li><strong>Units mixed into the value, and inconsistent with each other.</strong> Most of a Weight or Height column might be plain numbers, <code>72</code>, <code>1.70</code>, and so on, but one row breaks the pattern: <code>195 lbs</code> and <code>6 ft</code> instead of kilograms and metres, or a height like <code>178</code> sitting uncommented among a column of metres, really centimetres in disguise. R reads a whole column as text the moment a single cell in it isn’t a bare number, so it only takes one row like this to turn an otherwise clean numeric column into text throughout.</li>
<li><strong>Blank rows used for spacing.</strong> A blank row inserted purely to separate two sections becomes a row of missing values, <code>NA</code>, in every column, once imported.</li>
<li><strong>Notes written in a stray cell</strong>, off to the side of the actual table, with no column of their own. This can be a note about one specific patient, or, as with the colour above, a caption meant to explain something elsewhere in the sheet that never made it into a proper column.</li>
<li><strong>More than one table on a single sheet.</strong> R expects a sheet to be one table. A second, unrelated table lower down the same sheet gets read as more rows of the first table, and the result makes no sense.</li>
</ul>
<p><strong>Spreadsheet exercise (ILO 1).</strong> <code>data/05-prep2-messy-clinic.xlsx</code> is a small, made-up clinic visit log, built specifically to have every one of these problems at once. Open it in Excel, or whatever spreadsheet software you have.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Screenshot placeholder</strong> (<code>images/05-prep2-messy-spreadsheet.png</code>): <code>05-prep2-messy-clinic.xlsx</code> open in a spreadsheet application, showing the merged title row, the merged sub-header over the Weight and Height columns, the yellow-highlighted rows with no <code>Smoker</code> column anywhere in sight, and the second table below the gap.</p>
</div>
</div>
</div>
<p>Go through the sheet and list every feature above that you can find in it. Then build a clean version: one header row naming every column, one row per patient, weight and height as plain numbers in consistent units with the units moved into the column name instead of the value, a proper smoker column holding an actual word rather than a colour and a caption, no stray notes, and the second table (the follow-up schedule) either removed or saved as a completely separate file. Save your clean version as a <code>.csv</code> file. The Solutions section describes the fixes, but building the file yourself, in spreadsheet software, is the actual point of this exercise. There’s nothing to submit for it.</p>
</section>
</section>
<section id="finding-a-file-and-telling-r-where-it-is" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="finding-a-file-and-telling-r-where-it-is"><span class="header-section-number">2.4</span> Finding a file, and telling R where it is</h2>
<p>Before we can read anything into R, we need to know exactly where the file we want actually lives. This is the file system skill everything from here on assumes.</p>
<p><strong>Where downloads go.</strong> When you download a file from a browser, most browsers save it into a folder called <code>Downloads</code> by default, without asking. On Windows that’s usually <code>C:\Users\yourname\Downloads</code>; on a Mac it’s usually <code>/Users/yourname/Downloads</code>. If you can’t find a file you just downloaded, that folder is the first place to check, and it’s worth confirming where your own browser is set to save to, since some let you change it.</p>
<p><strong>Reading a path.</strong> A file path is a set of directions from somewhere fixed down to one specific file, one folder at a time, separated by slashes. <code>data/mph_nhanes_20241107.csv</code> reads as “the folder called <code>data</code>, then inside it the file called <code>mph_nhanes_20241107.csv</code>.” A longer path just has more folders to walk through before reaching the file.</p>
<p><strong>Copying a path.</strong> You’ll rarely type a full path out by hand; instead, you copy it straight from your file browser.</p>
<ul>
<li><strong>Windows:</strong> hold Shift and right-click the file, then choose <strong>Copy as path</strong>.</li>
<li><strong>macOS:</strong> right-click the file, then hold the <strong>Option</strong> key, which changes the menu, and choose <strong>Copy “filename” as Pathname</strong>.</li>
</ul>
<p><strong>Backslashes versus forward slashes.</strong> A path copied this way on Windows uses backslashes, <code>\</code>, for example <code>C:\Users\yourname\Documents\ies_mph\data\file.csv</code>. R uses forward slashes, <code>/</code>, instead, and treats a lone backslash as the start of a special character rather than a folder separator, so a pasted Windows path usually needs every <code>\</code> replaced with <code>/</code> before R will accept it.</p>
<p><strong>What a CSV actually is.</strong> Open a <code>.csv</code> file in a plain text editor, Notepad on Windows or TextEdit on a Mac, rather than in spreadsheet software, and you’ll see plain text: one line per row, values separated by commas. There’s no hidden formatting behind it, which is exactly why it’s such a safe format to hand between different pieces of software, R included.</p>
</section>
<section id="getting-data-in" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="getting-data-in"><span class="header-section-number">2.5</span> Getting data in</h2>
<section id="read_csv-and-here" class="level3" data-number="2.5.1">
<h3 data-number="2.5.1" class="anchored" data-anchor-id="read_csv-and-here"><span class="header-section-number">2.5.1</span> <code>read_csv()</code> and <code>here()</code></h3>
<p><code>readr</code>’s <code>read_csv()</code> reads a <code>.csv</code> file into R as a data frame. It needs a path telling it exactly where that file is, using the path skills from earlier in this chapter. Building that path with <code>here()</code>, from the <code>here</code> package, means the same code works on any machine, regardless of where the project folder actually sits on that machine’s disk: <code>here()</code> starts from the project folder and adds the pieces you give it, one folder at a time.</p>
<p>This chapter needs three packages: <code>readr</code> for reading files, <code>here</code> for building paths, and <code>ggplot2</code> for the plot at the end. As IES Week 4 explained, installing a package and loading it are two different actions, so unless you’ve installed these already, run this once in the console, not inside this document:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="fu">c</span>(<span class="st">"readr"</span>, <span class="st">"here"</span>, <span class="st">"ggplot2"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>After that, <code>library()</code> is all you need, in this session and every session after it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>library(here)</code> prints one line when it loads, which this book hides because it’s too wide to fit the page. In your own console it says <code>here() starts at ...</code> followed by the full path to your project folder. That’s worth reading the first time you see it, because it’s <code>here()</code> telling you exactly which folder it will build every path from. If that path isn’t the project folder you built in IES Week 4, nothing below will find its files, and this is where you’d find that out.</p>
</section>
<section id="four-things-that-go-wrong" class="level3" data-number="2.5.2">
<h3 data-number="2.5.2" class="anchored" data-anchor-id="four-things-that-go-wrong"><span class="header-section-number">2.5.2</span> Four things that go wrong</h3>
<p>Almost every import problem you’ll hit is one of four things. Each one below is deliberately broken, then fixed.</p>
<p><strong>A wrong filename.</strong> Close, but not exact:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107_data.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error:
! '/projects/ies_stats_ebook/data/mph_nhanes_20241107_data.csv' does
  not exist.</code></pre>
</div>
</div>
<p>The real file is called <code>mph_nhanes_20241107.csv</code>, no <code>_data</code> in the name. R’s message states plainly that the file doesn’t exist at the path it tried, which is exactly what IES Week 4’s “file does not exist” error type looks like with a real file behind it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>A path pasted straight from Windows Explorer.</strong> Shift+right-click → <em>Copy as path</em>, from earlier in this chapter, gives you a full path using backslashes, for example <code>C:\Users\yourname\Documents\new_folder\mph_nhanes_20241107.csv</code>. Paste that directly into R as a string, without changing anything:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="st">"C:\Users\yourname\Documents</span><span class="sc">\n</span><span class="st">ew_folder\mph_nhanes_20241107.csv"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error: '\U' used without hex digits in character string (&lt;input&gt;:1:14)</code></pre>
</div>
</div>
<p>This isn’t even a “file not found” error. It never gets that far. <code>\U</code> is one of a handful of backslash sequences R’s parser treats specially inside a string, and <code>\Users</code> isn’t a valid one, so R refuses to parse the string at all. Every Windows path copied this way starts with <code>C:\Users\...</code>, so this isn’t a rare edge case, it’s the default shape of a pasted Windows path. The fix from earlier in this chapter still applies: replace every backslash with a forward slash before using a path in R. Better still, once the path is inside the project folder, <code>here()</code> avoids the problem entirely, since you never type the backslash-filled part of the path at all.</p>
<p><strong>The right file, wrong location.</strong> Forgetting which subfolder the file lives in:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"mph_nhanes_20241107.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-error">
<pre><code>Error:
! '/projects/ies_stats_ebook/mph_nhanes_20241107.csv' does not
  exist.</code></pre>
</div>
</div>
<p>The filename is exactly right this time. What’s missing is <code>"data"</code>, the subfolder it actually lives in. R’s error message looks identical to the wrong-filename case above, which is worth noticing: the message tells you <em>that</em> nothing was found at that path, not <em>why</em> your path was wrong. You have to check that yourself.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>The wrong file type.</strong> <code>data/05-prep2-messy-clinic.xlsx</code>, from the exercise above, is an Excel file, not a CSV. Reading it with <code>read_csv()</code> doesn’t throw an error at all.</p>
<p>To see what actually came in, we need three functions. <code>dim()</code> reports how many rows and columns a dataset has, and <code>names()</code> lists its column names. Both get a proper introduction in the next section, where we use them on real data; here they’re just the quickest way to look. <code>substr()</code>, from base R, takes a piece of text and keeps only part of it, given a starting and an ending position: <code>substr(x, 1, 50)</code> keeps the first 50 characters and throws the rest away. We need it because the column name that comes back is far too long to print in full.</p>
<p>There’s one extra argument in the call below, <code>show_col_types = FALSE</code>, and it’s worth saying what it switches off rather than letting it slide past. <code>read_csv()</code> normally prints a short report of what it found and what type it guessed for each column. We meet that report properly in a moment, on the real data file, where it’s useful. Here it would just be several lines of nonsense about a file that hasn’t imported, so we turn it off to keep the broken result below the only thing on screen. That’s the only reason it’s there.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>messy_attempt <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"05-prep2-messy-clinic.xlsx"</span>),</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Multiple files in zip: reading '[Content_Types].xml'</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(messy_attempt)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">substr</span>(<span class="fu">names</span>(messy_attempt), <span class="dv">1</span>, <span class="dv">50</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "&lt;?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"y"</code></pre>
</div>
</div>
<p>No error, but nothing usable either: one column, zero rows, and a column name that’s a fragment of raw XML. An <code>.xlsx</code> file is actually a small zip archive of several XML files bundled together, and <code>read_csv()</code> has gone looking inside that archive and started reading one of those XML files as if it were plain text. This is the quietest kind of import failure there is: nothing crashes, nothing complains, and the result still looks like a data frame at a glance. Always check what actually came in, which is exactly what the next section is for.</p>
<p>Put right, all four attempts above collapse into the one call we actually want, and this is the real import we use for the rest of this book. The file holds <code>nhanes_mph</code>, an extract of a large American health survey in which adults were interviewed and then given a physical examination, so it carries measured values like cholesterol alongside things people reported about themselves. IES Week 7 introduces it properly, including one important simplification we make about it throughout. For today we only need it to be a real file with real data in it:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="the-block-of-output-youll-see" class="level3" data-number="2.5.3">
<h3 data-number="2.5.3" class="anchored" data-anchor-id="the-block-of-output-youll-see"><span class="header-section-number">2.5.3</span> The block of output you’ll see</h3>
<p>Run that line yourself and <code>read_csv()</code> prints eight lines the moment it finishes. This book hides them, because one of them is too wide to fit the page, so here they are as they’ll appear in your console:</p>
<pre><code>Rows: 41765 Columns: 27
── Column specification ────────────────────────────────
Delimiter: ","
chr  (3): smoking, phq.c, lcod
dbl (24): SEQN, age, gender, eth, edu, alc_wk, vpa_w, ...

ℹ Use `spec()` to retrieve the full column specification
  for this data.
ℹ Specify the column types or set `show_col_types = FALSE`
  to quiet this message.</code></pre>
<p>It looks like something went wrong. Nothing did. This is a <strong>message</strong>, not a warning and not an error, and it appears every single time <code>read_csv()</code> reads a file successfully. It’s worth reading once, properly, because it’s the first thing you know about a dataset you’ve never opened.</p>
<p><code>Rows: 41765 Columns: 27</code> is the size of what came in. That’s the same fact <code>dim()</code> gives us below, arriving before we ask for it. If a file you expected to have a few hundred rows reports three, you’ve learned that here rather than ten minutes later.</p>
<p><code>Delimiter: ","</code> is <code>read_csv()</code> confirming it split each line at commas, which is what the “comma” in “comma separated values” means, and what we saw for ourselves earlier in this chapter when we opened a CSV in a text editor.</p>
<p>Then the column specification: <code>chr (3)</code> lists three columns read as character, that is text, and <code>dbl (24)</code> lists twenty-four read as numbers. <code>dbl</code> is short for “double”, which is R’s ordinary way of storing a number that can have decimal places. This is <code>read_csv()</code> telling us what it <em>guessed</em>, one column at a time, and that guess is the thing worth checking. Notice <code>smoking</code> and <code>phq.c</code> sitting in the character list, and <code>gender</code> and <code>eth</code> sitting in the number list, and hold onto that: it comes back in the next section but one.</p>
<p>The two lines beginning with an <code>ℹ</code> are <code>read_csv()</code> offering you a way to see the full specification, and a way to make the whole message go away. That second one is <code>show_col_types = FALSE</code>, the argument we used on the broken <code>.xlsx</code> import above. Now you know what it silences. Use it when you already know what’s in a file and don’t want the report again, not to make untidy output go away, because “untidy output” and “the only warning you were going to get” often look identical.</p>
</section>
<section id="a-first-look" class="level3" data-number="2.5.4">
<h3 data-number="2.5.4" class="anchored" data-anchor-id="a-first-look"><span class="header-section-number">2.5.4</span> A first look</h3>
<p>The message already told us the size and the column types. Four functions let us check that against what we actually have.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(nhanes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 41765    27</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(nhanes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "SEQN"     "age"      "gender"   "eth"      "edu"      "smoking" 
 [7] "alc_wk"   "vpa_w"    "mpa_w"    "wal_r"    "vpa_r"    "mpa_r"   
[13] "mpa_t"    "vpa_t"    "met_w"    "met_r"    "met_t"    "sed"     
[19] "chol"     "phq"      "phq.c"    "blm.cvd"  "dth"      "lcod"    
[25] "ucod_dm"  "ucod_ht"  "fu_month"</code></pre>
</div>
</div>
<p><code>dim()</code> gives rows, then columns. <code>names()</code> lists every column name, in order, useful for checking a name before you type it.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(nhanes)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 27
   SEQN   age gender   eth   edu smoking  alc_wk vpa_w mpa_w wal_r vpa_r
  &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1    12    37      1     3     3 Never     0.460    NA    NA    NA    NA
2    20    23      2     1     1 Previous  3        NA    NA    NA    NA
3    34    38      2     4     2 Current   1        NA    NA    NA    NA
4    66    37      1     1     3 Never    NA        NA    NA    NA    NA
5    69    27      1     4     3 Never     2        NA    NA    NA    NA
6    81    30      1     3     3 Never     1        NA    NA    NA    NA
# ℹ 16 more variables: mpa_r &lt;dbl&gt;, mpa_t &lt;dbl&gt;, vpa_t &lt;dbl&gt;, met_w &lt;dbl&gt;,
#   met_r &lt;dbl&gt;, met_t &lt;dbl&gt;, sed &lt;dbl&gt;, chol &lt;dbl&gt;, phq &lt;dbl&gt;,
#   phq.c &lt;chr&gt;, blm.cvd &lt;dbl&gt;, dth &lt;dbl&gt;, lcod &lt;chr&gt;, ucod_dm &lt;dbl&gt;,
#   ucod_ht &lt;dbl&gt;, fu_month &lt;dbl&gt;</code></pre>
</div>
</div>
<p><code>head()</code> prints the first six rows, so you can eyeball what real values actually look like.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nhanes<span class="sc">$</span>age)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  18.00   31.00   46.00   47.52   63.00   85.00 </code></pre>
</div>
</div>
<p><code>summary()</code>, run on one column, gives its minimum, maximum, quartiles, and mean in one line, plus a count of missing values if there are any. Run on the whole data frame instead of one column, it repeats this for every column at once, which is a fast way to eyeball the whole dataset in one go.</p>
<p>Look at <code>gender</code> and <code>smoking</code> in the output above. <code>gender</code> is a plain number, 1 or 2, standing in for a category. <code>smoking</code> is already text, “Never”, “Previous”, or “Current”. Neither is a proper R factor yet, a category R actually understands as one. IES Week 7 turns both, and four more columns like them, into real factors, checked against the dictionary file. For now we’re only looking, not changing anything.</p>
</section>
<section id="when-r-guesses-the-wrong-type" class="level3" data-number="2.5.5">
<h3 data-number="2.5.5" class="anchored" data-anchor-id="when-r-guesses-the-wrong-type"><span class="header-section-number">2.5.5</span> When R guesses the wrong type</h3>
<p><code>read_csv()</code> decides each column’s type by looking at the values in it. Most of the time that guess is right. It goes wrong in exactly the situation the messy spreadsheet exercise built on purpose: a column that’s plain numbers for every patient except one, who was recorded as <code>"195 lbs"</code> instead of a number in kilograms. R has no way to know that <code>"lbs"</code> should be split off, converted, and the rest treated as a number. It just sees text and stores the whole column as text, one stray row is all it takes. This is why the clean version of that spreadsheet needed every patient converted to the same unit, with that unit moved into the column <em>name</em> (<code>weight_kg</code>) and out of every individual <em>value</em>: it’s the only way <code>read_csv()</code> ends up with a column it can actually calculate on.</p>
</section>
<section id="spotting-missing-data" class="level3" data-number="2.5.6">
<h3 data-number="2.5.6" class="anchored" data-anchor-id="spotting-missing-data"><span class="header-section-number">2.5.6</span> Spotting missing data</h3>
<p><code>is.na()</code> checks each value in a vector and returns <code>TRUE</code> where it’s missing, <code>FALSE</code> where it isn’t. <code>sum()</code> on that result counts the <code>TRUE</code>s, since R treats <code>TRUE</code> as 1 and <code>FALSE</code> as 0 when you add them up.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(nhanes<span class="sc">$</span>vpa_w))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7354</code></pre>
</div>
</div>
<p>That’s how many participants have no value recorded for <code>vpa_w</code>, vigorous physical activity at work, out of 41,765 participants in total. <code>nrow()</code>, from base R, returns just the row count on its own, the same number <code>dim()</code> gives as its first value above, useful whenever we want the total on its own rather than alongside the column count. It’s a real gap, not a rounding artefact, and it matters: whatever we go on to calculate from <code>vpa_w</code> only ever describes the participants who actually have a value, and we should say so out loud whenever we report it, rather than letting it pass silently.</p>
</section>
<section id="using-the-dictionary-file" class="level3" data-number="2.5.7">
<h3 data-number="2.5.7" class="anchored" data-anchor-id="using-the-dictionary-file"><span class="header-section-number">2.5.7</span> Using the dictionary file</h3>
<p><code>nhanes_mph</code> arrives as two separate files. We’ve already read the data itself. The second file names every column and states what it means, and it’s every bit as important as the data. Reading it prints the same column specification message we just unpacked, saying two columns of text this time instead of twenty-seven columns of mixed types. This book hides it from here on, since it says the same kind of thing every time and we’ve now read one properly. You’ll still see it in your own console, and it’s still worth a glance:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dictionary <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107_dictionary.csv"</span>))</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>dictionary</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 27 × 2
   `Variable names` Description                                             
   &lt;chr&gt;            &lt;chr&gt;                                                   
 1 SEQN             Participant identifier                                  
 2 age              Age in years                                            
 3 gender           Gender (1=Male; 2=Female)                               
 4 eth              Ethnicity (1=Mexican; 2=Other Hispanic; 3=White; 4=Blac…
 5 edu              Educaton (1=Less than high school; 2=high school gradua…
 6 smoking          Smoking status (Never/Previous/Current)                 
 7 alc_wk           Alcohol drinking per week                               
 8 vpa_w            Vigourous physical activity (hour/day) at work          
 9 mpa_w            Moderate physical activity (hour/day) at work           
10 wal_r            Walking (hour/day) outside work                         
# ℹ 17 more rows</code></pre>
</div>
</div>
<p>The dictionary’s first column is called <code>Variable names</code>, with a space in it, so referring to it needs backticks, exactly as IES Week 4 covered. <code>%in%</code>, from the same chapter, tests whether each value is a member of a set. Put inside square brackets after a data frame’s column, with the row’s index implied, this keeps only the rows where the condition is true:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>dictionary[dictionary<span class="sc">$</span><span class="st">`</span><span class="at">Variable names</span><span class="st">`</span> <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"age"</span>, <span class="st">"chol"</span>, <span class="st">"smoking"</span>), ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  `Variable names` Description                            
  &lt;chr&gt;            &lt;chr&gt;                                  
1 age              Age in years                           
2 smoking          Smoking status (Never/Previous/Current)
3 chol             Total cholesterol (mmol/L)             </code></pre>
</div>
</div>
<p>That’s the habit worth building now: when a column’s meaning isn’t obvious from its name, the answer lives in this file, not in a guess. IES Week 7 uses this same file to build proper factors out of six of these columns; for today, just knowing how to look one up is enough.</p>
</section>
</section>
<section id="a-first-analysis-and-your-first-script" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="a-first-analysis-and-your-first-script"><span class="header-section-number">2.6</span> A first analysis, and your first script</h2>
<section id="one-summary-statistic" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="one-summary-statistic"><span class="header-section-number">2.6.1</span> One summary statistic</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nhanes<span class="sc">$</span>chol, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.973316</code></pre>
</div>
</div>
<p><code>chol</code> is total cholesterol, in mmol/L, and 2,589 participants have no value recorded for it, the same kind of gap <code>vpa_w</code> had above. <code>na.rm = TRUE</code> drops those missing values before averaging the rest, exactly as it did back in IES Week 4’s <code>mean()</code> example. Leave it out and the whole calculation returns <code>NA</code>, since R won’t silently guess what a missing value should have been.</p>
</section>
<section id="a-first-taste-of-a-grouped-summary" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="a-first-taste-of-a-grouped-summary"><span class="header-section-number">2.6.2</span> A first taste of a grouped summary</h3>
<p><code>nhanes$chol</code> pulls the whole cholesterol column out as a bare vector, exactly as <code>$</code> did in IES Week 4. Adding square brackets straight after it, with a condition inside, keeps only the values where that condition is <code>TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nhanes<span class="sc">$</span>chol[nhanes<span class="sc">$</span>smoking <span class="sc">==</span> <span class="st">"Never"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs 
  1.780   4.220   4.890   4.968   5.610  15.830    1839 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(nhanes<span class="sc">$</span>chol[nhanes<span class="sc">$</span>smoking <span class="sc">==</span> <span class="st">"Current"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.     NAs 
  1.530   4.220   4.890   4.996   5.660  15.900     882 </code></pre>
</div>
</div>
<p>That’s a genuine grouped summary, built entirely from tools already familiar: <code>$</code>, <code>==</code>, and now <code>[</code> with a condition inside it. It works, but it’s clunky already with just two groups, and <code>smoking</code> has three. IES Week 7 introduces <code>group_by()</code> and <code>summarise()</code>, a far nicer way to do exactly this for as many groups as you like, in one line instead of several. This is only a preview of what’s coming, not the tool you’ll actually use going forward.</p>
</section>
<section id="a-first-taste-of-a-plot" class="level3" data-number="2.6.3">
<h3 data-number="2.6.3" class="anchored" data-anchor-id="a-first-taste-of-a-plot"><span class="header-section-number">2.6.3</span> A first taste of a plot</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes, <span class="fu">aes</span>(<span class="at">x =</span> chol)) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2589 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-prep2_files/figure-html/plot-preview-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><code>ggplot2</code> code is joined with <code>+</code>, not the pipe. That’s a real inconsistency in R, not a mistake in this book, and IES Week 7 explains why and unpacks the rest of the grammar properly. For today, just notice the shape: cholesterol piles up around 4 to 6 mmol/L, with a long tail of higher values trailing off to the right.</p>
</section>
<section id="that-warning-above-the-plot" class="level3" data-number="2.6.4">
<h3 data-number="2.6.4" class="anchored" data-anchor-id="that-warning-above-the-plot"><span class="header-section-number">2.6.4</span> That warning above the plot</h3>
<p>The plot came with a line starting <code>Warning:</code>, saying it removed 2,589 rows. Read it, because we’ll see this one a lot, and then don’t worry about it.</p>
<p>First, a warning is not an error. An error means R gave up and produced nothing. A warning means R did the job and is telling you something about how. The plot is there and it’s fine.</p>
<p>Second, look at the number. It’s 2,589, exactly the count of participants with no cholesterol value that we found a moment ago. That’s not a coincidence, it’s the same fact arriving twice. A histogram puts each participant somewhere along the axis, and a missing value has no “somewhere” to go, so <code>ggplot2</code> left those participants out and told us how many it dropped.</p>
<p><strong>Why we leave these warnings switched on.</strong> R can be told to hide them, and plenty of people do, because they look untidy. This book doesn’t, and neither should you for now. That warning is a free count of how much of your data a plot is actually based on. Hide it, and a plot built on half your dataset looks exactly like a plot built on all of it. It’s the same reason we write <code>na.rm = TRUE</code> deliberately and say what it dropped, rather than typing it out of habit until it stops registering.</p>
<p><strong>When it does need attention.</strong> The number is the thing to check, not the warning itself. Compare it against what you expect, the way we just did with <code>is.na()</code>. If it matches, carry on. If it’s much larger than expected, stop and find out why before trusting anything the plot shows: usually it means the wrong column, an import that didn’t go as planned, or an earlier step that threw away more rows than intended. And whenever you report a result, say how many observations it’s based on and how many were missing. A warning R printed for you is not the same as a reader being told.</p>
</section>
<section id="from-console-to-script" class="level3" data-number="2.6.5">
<h3 data-number="2.6.5" class="anchored" data-anchor-id="from-console-to-script"><span class="header-section-number">2.6.5</span> From console to script</h3>
<p>Everything we’ve done so far in this chapter has been one line at a time. That’s the right way to <em>try</em> something: type it in the console, look at what comes back, fix it if it’s wrong. But IES Week 4 already made the argument against leaving it there. You will need to do this again, and you will not remember what you typed.</p>
<p>So the working habit for the rest of this course is two steps, not one. Try the line in the console until it does what you want. Then move the line that worked into a script, and save it. The console is where you experiment; the script is what you keep.</p>
<p>To build one now:</p>
<ol type="1">
<li>In RStudio, go to <strong>File → New File → R Script</strong>. A blank file opens in the source pane, top-left.</li>
<li>Type the lines you want to keep. For a first script, that’s the <code>library()</code> calls, the <code>read_csv()</code> line, one summary, and one plot.</li>
<li>Save it into the <code>scripts/</code> folder you built in IES Week 4, with a name that follows its conventions: no spaces, no <code>&amp;</code> or <code>#</code>, something that says what it does. <code>first_analysis.R</code> is fine. <code>Untitled1.R</code> is not.</li>
</ol>
<p>Here’s what a complete first script looks like, start to finish. Nothing in it is new; it’s the pieces from earlier in this chapter, collected in the order they need to run:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107.csv"</span>))</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nhanes<span class="sc">$</span>chol, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(nhanes<span class="sc">$</span>chol))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes, <span class="fu">aes</span>(<span class="at">x =</span> chol)) <span class="sc">+</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Notice the shape of it. The <code>library()</code> calls come first, because nothing below them works until the packages are loaded. The <code>read_csv()</code> line comes next, because every line after it needs <code>nhanes</code> to exist. A script runs top to bottom, so the order isn’t decoration, it’s the thing that makes it work.</p>
</section>
<section id="proving-it-actually-works" class="level3" data-number="2.6.6">
<h3 data-number="2.6.6" class="anchored" data-anchor-id="proving-it-actually-works"><span class="header-section-number">2.6.6</span> Proving it actually works</h3>
<p>Here’s the part people skip, and it’s the part that matters. A script that runs on your machine right now, in a session where you’ve been typing for an hour, is not yet proof of anything. Half of what it needs might already be sitting in memory from something you typed and forgot.</p>
<p>So test it properly. In RStudio, go to <strong>Session → Restart R</strong>. That throws away every object and every loaded package, leaving you with an empty session, exactly like the one a colleague, a marker, or you-in-six-months would start from. Now run your script from the top.</p>
<p>If it runs clean, the script is genuinely self-contained. If it fails, the error tells you precisely what you’d forgotten to write down, and the fix belongs <em>in the script</em>, not typed into the console again. That restart is the reproducibility argument from IES Week 4, made concrete: not “scripts are good practice” but “here is how you find out whether yours actually is one.”</p>
</section>
<section id="how-this-book-is-put-together" class="level3" data-number="2.6.7">
<h3 data-number="2.6.7" class="anchored" data-anchor-id="how-this-book-is-put-together"><span class="header-section-number">2.6.7</span> How this book is put together</h3>
<p>Every chapter follows the same shape: learning objectives at the top, then worked content with the code and its output both visible, then a full worked example, then numbered exercises mapped back to those objectives. Solutions sit in a collapsed section at the very end, so you can have a real go before you look.</p>
<p>The way to use it is to work along in a script of your own. Don’t read the code, and don’t copy and paste it either. Type it, run it, and see the same output appear in your console. When something breaks, that’s not you falling behind, that’s the part you’re about to learn something from.</p>
</section>
</section>
<section id="exercises" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="exercises"><span class="header-section-number">2.7</span> Exercises</h2>
<p><strong>Exercise 1</strong> (ILO 2). This <code>read_csv()</code> call is supposed to read the dictionary file but doesn’t work:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_dictionary.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Work out what’s wrong with the path and write the corrected call.</p>
<p><strong>Exercise 2</strong> (ILO 3). Check <code>mpa_w</code> (moderate physical activity at work): find its type with <code>class()</code>, and count how many values are missing with <code>is.na()</code> and <code>sum()</code>.</p>
<p><strong>Exercise 3</strong> (ILO 4). Produce one summary statistic and one plot for <code>wal_r</code> (walking, hours/day, outside work). Remember <code>na.rm = TRUE</code> if it turns out to have missing values.</p>
<p><strong>Exercise 4</strong> (ILO 4). Collect your answer to Exercise 3 into a proper script. Open a new R script, and write into it everything needed to go from a completely empty session to that summary and that plot: the <code>library()</code> calls, the <code>read_csv()</code> line, then the summary and the plot themselves. Save it into your <code>scripts/</code> folder with a sensible name.</p>
<p>Then test it the way this chapter described. Go to <strong>Session → Restart R</strong>, and run your script from the top. If it errors, read the message, work out what the fresh session was missing, and add that line to the script rather than typing it into the console. Repeat until it runs clean from a restart. That is the point of the exercise, not the summary itself.</p>
</section>
<section id="self-check" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="self-check"><span class="header-section-number">2.8</span> Self-check</h2>
<p>Five questions on the concepts this chapter leans on hardest: paths, file types, and reading a real import problem. Answers are in the Solutions section below.</p>
<p><strong>1.</strong> <code>read_csv(here("data", "mhp_nhanes_20241107.csv"))</code> fails, even though <code>mph_nhanes_20241107.csv</code> really is in the <code>data</code> folder. Which of the four import failures is this?</p>
<ol type="a">
<li>The file is the wrong type</li>
<li>A path pasted with backslashes</li>
<li>A wrong filename, here a typo (<code>mhp</code> instead of <code>mph</code>)</li>
<li>The file is in the wrong folder</li>
</ol>
<p><strong>2.</strong> What’s the actual difference between <code>dim(nhanes)</code> and <code>names(nhanes)</code>?</p>
<ol type="a">
<li>They return exactly the same information in two formats</li>
<li><code>dim()</code> gives the number of rows and columns; <code>names()</code> lists every column name</li>
<li><code>names()</code> gives row and column counts; <code>dim()</code> lists column names</li>
<li><code>dim()</code> only works after <code>names()</code> has been run first</li>
</ol>
<p><strong>3.</strong> <code>sum(is.na(nhanes$vpa_w))</code> returns <code>7354</code>. What does that number actually mean?</p>
<ol type="a">
<li>The mean value of <code>vpa_w</code></li>
<li>7,354 participants have <code>vpa_w</code> recorded as exactly zero</li>
<li>7,354 participants have no value recorded for <code>vpa_w</code></li>
<li>There are 7,354 participants in the dataset in total</li>
</ol>
<p><strong>4.</strong> <code>read_csv()</code> is used to read both <code>mph_nhanes_20241107.csv</code> and <code>mph_nhanes_20241107_dictionary.csv</code>, in two separate calls. Why two calls, and not one?</p>
<ol type="a">
<li><code>read_csv()</code> can only read one row at a time</li>
<li>They’re two separate files, each holding a different table, so each needs its own call</li>
<li>The dictionary file is not really needed, but the call is included anyway</li>
<li><code>read_csv()</code> automatically finds and reads both once you name one of them</li>
</ol>
<p><strong>5.</strong> Reading <code>05-prep2-messy-clinic.xlsx</code> with <code>read_csv()</code> produces a data frame with 1 column and 0 rows, and no error message. What does that tell you?</p>
<ol type="a">
<li>The file is empty</li>
<li><code>read_csv()</code> refuses to read <code>.xlsx</code> files and stops immediately</li>
<li><code>.xlsx</code> is the wrong file type for <code>read_csv()</code>, and the lack of an error is exactly why you always check what actually came in</li>
<li>The import worked correctly and the file genuinely has one column</li>
</ol>
</section>
<section id="writing-exercise" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="writing-exercise"><span class="header-section-number">2.9</span> Writing exercise</h2>
<p>Using the mean and the histogram from Exercise 3, write a short paragraph, about 60 words, describing <code>wal_r</code> as you would in the results section of a report. State the mean and its units, say how many participants have no value recorded, and describe the shape of the distribution the histogram shows. This is the smallest version of a habit the rest of this book builds on: a number on its own, with no sentence around it, is not yet a result.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Spreadsheet exercise</strong></p>
<p>The fixes needed, matching each problem named earlier: split the merged title row and the merged “Measurements” sub-header back into one header row naming every column individually; convert every patient’s weight and height to the same units (kilograms and metres), then move those units out of the values and into the column names instead (<code>weight_kg</code>, <code>height_m</code>), leaving plain numbers behind; add a proper Smoker column holding an actual word (“Yes”/“No”), decoded from which rows were highlighted and the caption that explained what the highlighting meant; delete both blank spacer rows; delete or relocate the stray note about Patient 5’s missed follow-up, since it belongs in its own column, or nowhere in this table at all; and either delete the second table (the follow-up schedule) or save it as its own, separate CSV file, since one sheet should hold one table.</p>
<p><strong>Exercise 1</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107_dictionary.csv"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 27 × 2
   `Variable names` Description                                             
   &lt;chr&gt;            &lt;chr&gt;                                                   
 1 SEQN             Participant identifier                                  
 2 age              Age in years                                            
 3 gender           Gender (1=Male; 2=Female)                               
 4 eth              Ethnicity (1=Mexican; 2=Other Hispanic; 3=White; 4=Blac…
 5 edu              Educaton (1=Less than high school; 2=high school gradua…
 6 smoking          Smoking status (Never/Previous/Current)                 
 7 alc_wk           Alcohol drinking per week                               
 8 vpa_w            Vigourous physical activity (hour/day) at work          
 9 mpa_w            Moderate physical activity (hour/day) at work           
10 wal_r            Walking (hour/day) outside work                         
# ℹ 17 more rows</code></pre>
</div>
</div>
<p>The folder and filename were both fine. The problem was the letters <code>mph</code> typed as <code>mhp</code>.</p>
<p><strong>Exercise 2</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(nhanes<span class="sc">$</span>mpa_w)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "numeric"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(nhanes<span class="sc">$</span>mpa_w))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7391</code></pre>
</div>
</div>
<p><strong>Exercise 3</strong></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nhanes<span class="sc">$</span>wal_r, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2060187</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(nhanes<span class="sc">$</span>wal_r))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 7347</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes, <span class="fu">aes</span>(<span class="at">x =</span> wal_r)) <span class="sc">+</span></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7347 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05-prep2_files/figure-html/sol-ex3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Exercise 4</strong></p>
<p>The finished script, in full. Saved as <code>scripts/wal_r_analysis.R</code>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">"data"</span>, <span class="st">"mph_nhanes_20241107.csv"</span>))</span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(nhanes<span class="sc">$</span>wal_r, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">is.na</span>(nhanes<span class="sc">$</span>wal_r))</span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes, <span class="fu">aes</span>(<span class="at">x =</span> wal_r)) <span class="sc">+</span></span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.5</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The two lines people most often leave out are the ones that were already true before they started: <code>library(readr)</code> and the <code>read_csv()</code> call. Both had been run earlier in the session, so <code>nhanes</code> existed and <code>read_csv()</code> worked, and neither felt like part of “the analysis.” After a restart, neither is true any more, and the script fails on its first real line with <code>could not find function "read_csv"</code> or <code>object 'nhanes' not found</code>, both of which IES Week 4 covered. That’s exactly what the restart is for: it finds the assumptions you didn’t know you were making.</p>
<p><strong>Self-check answers</strong></p>
<ol type="1">
<li><strong>c.</strong> <code>mhp</code> versus <code>mph</code> is a plain typo in the filename, not a folder problem, a file-type problem, or a backslash problem.</li>
<li><strong>b.</strong> <code>dim()</code> returns row and column counts. <code>names()</code> returns the column names themselves. Neither substitutes for the other.</li>
<li><strong>c.</strong> <code>is.na()</code> marks each missing value <code>TRUE</code>, and <code>sum()</code> adds those up. The number is a count of participants with no recorded value, nothing about the values that are present.</li>
<li><strong>b.</strong> <code>mph_nhanes_20241107.csv</code> and <code>mph_nhanes_20241107_dictionary.csv</code> are two separate files on disk, each holding a different table, so each needs its own <code>read_csv()</code> call.</li>
<li><strong>c.</strong> <code>.xlsx</code> is a zip archive of XML files, not a CSV, so <code>read_csv()</code> produces nonsense rather than a real dataset. The absence of an error is exactly the trap: always check what actually came in after reading a file, not just whether it “worked.” <code>dim()</code>, used earlier in this chapter, is one way to do that. IES Week 7 introduces a second, <code>glimpse()</code> from <code>dplyr</code>, which shows every column with its type and first few values in one compact layout, better suited to a wide dataset like <code>nhanes_mph</code> than <code>dim()</code> alone.</li>
</ol>
<p><strong>Writing exercise (sample answer)</strong></p>
<p>Participants reported a mean of 0.21 hours/day of walking outside work (<code>wal_r</code>), based on the 34,418 participants with a value recorded; 7,347 had none. The distribution is heavily right-skewed: most participants reported no walking outside work at all, and a small number reported several hours a day, pulling the mean above what a typical participant’s value actually looks like.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/04-prep1.html" class="pagination-link" aria-label="R and R Studio (IES Week 4)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R and R Studio (IES Week 4)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/07-descriptive.html" class="pagination-link" aria-label="Describing and visualising data (IES Week 7)">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing and visualising data (IES Week 7)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>