<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Hypothesis tests and measures of association (Week 9) – IES Statistical Labs</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../chapters/10-regression.html" rel="next">
<link href="../chapters/08-estimation.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-3294577322a5a8aac4f27c9836f2d0c7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/09-comparison.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis tests and measures of association (Week 9)</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header sidebar-header-stacked">
      <a href="../index.html" class="sidebar-logo-link">
      </a>
    <div class="sidebar-title mb-0 py-0">
      <a href="../">IES Statistical Labs</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-prep1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R and R Studio (Week 4)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-prep2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data and data handling (Week 5)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/07-descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Describing and visualising data (Week 7)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/08-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimation, precision, and sample size (Week 8)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/09-comparison.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis tests and measures of association (Week 9)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/10-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression (Week 10)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/11-adjustment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Multiple linear and logistic regression (Week 11)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/12-summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Summary</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/99-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Glossary</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#chapter-intended-learning-outcomes" id="toc-chapter-intended-learning-outcomes" class="nav-link active" data-scroll-target="#chapter-intended-learning-outcomes"><span class="header-section-number">5.1</span> Chapter intended learning outcomes</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup"><span class="header-section-number">5.2</span> Setup</a></li>
  <li><a href="#the-logic-of-a-test" id="toc-the-logic-of-a-test" class="nav-link" data-scroll-target="#the-logic-of-a-test"><span class="header-section-number">5.3</span> The logic of a test</a></li>
  <li><a href="#one-sample-t-test-total-cholesterol-against-a-clinical-benchmark" id="toc-one-sample-t-test-total-cholesterol-against-a-clinical-benchmark" class="nav-link" data-scroll-target="#one-sample-t-test-total-cholesterol-against-a-clinical-benchmark"><span class="header-section-number">5.4</span> One-sample t-test: total cholesterol against a clinical benchmark</a></li>
  <li><a href="#paired-t-test-two-domains-of-activity-in-one-person" id="toc-paired-t-test-two-domains-of-activity-in-one-person" class="nav-link" data-scroll-target="#paired-t-test-two-domains-of-activity-in-one-person"><span class="header-section-number">5.5</span> Paired t-test: two domains of activity in one person</a></li>
  <li><a href="#a-non-parametric-alternative-the-wilcoxon-signed-rank-test" id="toc-a-non-parametric-alternative-the-wilcoxon-signed-rank-test" class="nav-link" data-scroll-target="#a-non-parametric-alternative-the-wilcoxon-signed-rank-test"><span class="header-section-number">5.6</span> A non-parametric alternative: the Wilcoxon signed-rank test</a></li>
  <li><a href="#independent-samples-t-test-cholesterol-by-gender" id="toc-independent-samples-t-test-cholesterol-by-gender" class="nav-link" data-scroll-target="#independent-samples-t-test-cholesterol-by-gender"><span class="header-section-number">5.7</span> Independent-samples t-test: cholesterol by gender</a></li>
  <li><a href="#chi-squared-test-strep_tbs-primary-result" id="toc-chi-squared-test-strep_tbs-primary-result" class="nav-link" data-scroll-target="#chi-squared-test-strep_tbs-primary-result"><span class="header-section-number">5.8</span> Chi-squared test: <code>strep_tb</code>’s primary result</a></li>
  <li><a href="#fishers-exact-test" id="toc-fishers-exact-test" class="nav-link" data-scroll-target="#fishers-exact-test"><span class="header-section-number">5.9</span> Fisher’s exact test</a></li>
  <li><a href="#risk-ratios-and-odds-ratios-with-confidence-intervals" id="toc-risk-ratios-and-odds-ratios-with-confidence-intervals" class="nav-link" data-scroll-target="#risk-ratios-and-odds-ratios-with-confidence-intervals"><span class="header-section-number">5.10</span> Risk ratios and odds ratios, with confidence intervals</a></li>
  <li><a href="#gtsummarytbl_summary-with-a-test-attached" id="toc-gtsummarytbl_summary-with-a-test-attached" class="nav-link" data-scroll-target="#gtsummarytbl_summary-with-a-test-attached"><span class="header-section-number">5.11</span> <code>gtsummary::tbl_summary()</code> with a test attached</a></li>
  <li><a href="#worked-example-sedentary-time-by-gender" id="toc-worked-example-sedentary-time-by-gender" class="nav-link" data-scroll-target="#worked-example-sedentary-time-by-gender"><span class="header-section-number">5.12</span> Worked example: sedentary time by gender</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">5.13</span> Exercises</a></li>
  <li><a href="#writing-exercise" id="toc-writing-exercise" class="nav-link" data-scroll-target="#writing-exercise"><span class="header-section-number">5.14</span> Writing exercise</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-09-comparison" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Hypothesis tests and measures of association (Week 9)</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>A confidence interval says how precise an estimate is. It doesn’t say whether the effect behind it is distinguishable from none at all: two groups’ cholesterol means could sit half a millimole apart with intervals that overlap, and whether that gap is a real difference or ordinary sampling noise is exactly the question Chapter 4 leaves open. A hypothesis test closes it, and gets reported alongside the interval rather than in place of it. Binary outcomes raise a version of the same question the descriptive statistics from Chapter 3 can’t answer on their own: is a health outcome more common in one group than another, and by how much? The risk ratio and the odds ratio from epidemiology measure that, and here we attach a confidence interval and a p-value to each.</p>
<p>Every test in this chapter runs on the same logic underneath: a null hypothesis, an alternative, a test statistic, and a p-value stating how surprising the observed data would be if the null were actually true. Which test applies depends on the shape of the data in front of us, one measurement per person or two, one group or several, continuous or count, and telling those apart correctly matters as much as running the test itself. Reported together, an effect size, its 95% confidence interval, and a p-value make up the standard this book writes results in from here on.</p>
<section id="chapter-intended-learning-outcomes" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="chapter-intended-learning-outcomes"><span class="header-section-number">5.1</span> Chapter intended learning outcomes</h2>
<p>By the end of this chapter you will be able to:</p>
<ol type="1">
<li>Perform and interpret a one-sample, paired, and independent-samples t-test using <code>t.test()</code></li>
<li>Construct a contingency table and perform a chi-squared test using <code>table()</code> and <code>chisq.test()</code></li>
<li>Determine when the above tests are valid, and when a non-parametric or exact alternative is needed (<code>wilcox.test()</code>, <code>fisher.test()</code>)</li>
<li>Calculate risk ratios and odds ratios with confidence intervals using <code>epitools::riskratio()</code> and <code>epitools::oddsratio()</code></li>
<li>Write up a test result in an appropriate academic style</li>
</ol>
</section>
<section id="setup" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="setup"><span class="header-section-number">5.2</span> Setup</h2>
<p>As in Chapters 3 and 4, we read the data with <code>read_csv()</code> and turn the six coded variables into factors against the dictionary. We also bring back <code>strep_tb</code>, from the <code>medicaldata</code> package, for the categorical half of this chapter.</p>
<p>This chapter adds one new package, <code>epitools</code>. Install it with <code>install.packages('epitools')</code> in the console, the same way as any other package, if it isn’t on your machine already. Once it’s installed, <code>library(epitools)</code> below makes its functions available for this session.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(here)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(medicaldata)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(epitools)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'mph_nhanes_20241107.csv'</span>))</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>dictionary <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="fu">here</span>(<span class="st">'data'</span>, <span class="st">'mph_nhanes_20241107_dictionary.csv'</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>nhanes <span class="ot">&lt;-</span> nhanes <span class="sc">|&gt;</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">gender =</span> <span class="fu">factor</span>(gender,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>),</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Male'</span>, <span class="st">'Female'</span>)),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">eth =</span> <span class="fu">factor</span>(eth,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>, <span class="dv">5</span>),</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Mexican American'</span>, <span class="st">'Other Hispanic'</span>, <span class="st">'White'</span>, <span class="st">'Black'</span>, <span class="st">'Others'</span>)),</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">edu =</span> <span class="fu">factor</span>(edu,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>),</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Less than high school'</span>, <span class="st">'High school graduate'</span>, <span class="st">'Above high school'</span>)),</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoking =</span> <span class="fu">factor</span>(smoking,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'Never'</span>, <span class="st">'Previous'</span>, <span class="st">'Current'</span>)),</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">phq.c =</span> <span class="fu">factor</span>(phq.c,</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">'0 Normal'</span>, <span class="st">'1 Mild symptoms'</span>, <span class="st">'2 Possible depression'</span>),</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'Normal'</span>, <span class="st">'Mild symptoms'</span>, <span class="st">'Possible depression'</span>),</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">ordered =</span> <span class="cn">TRUE</span>),</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">blm.cvd =</span> <span class="fu">factor</span>(blm.cvd,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>      <span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>),</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">'No'</span>, <span class="st">'Yes'</span>))</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This is the same recode we introduced in Chapters 3 and 4. See Chapter 3 for the reasoning behind each variable.</p>
</section>
<section id="the-logic-of-a-test" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="the-logic-of-a-test"><span class="header-section-number">5.3</span> The logic of a test</h2>
<p>A classical hypothesis test starts from two competing statements about the <strong>population</strong>. The <strong>null hypothesis</strong>, written H0, says there’s nothing going on: no difference between groups, or no association between variables. The exact wording depends on what is being tested, but it always describes the population, never the sample we happen to have measured. The <strong>alternative hypothesis</strong>, H1, says there is a difference. A one-sided alternative hypothesis, specifying the direction of the difference in advance, exists too, but is rarely used in practice; every test in this chapter uses the two-sided form. A test never proves the null hypothesis true. It only asks whether the pattern shown from the sample is surprising enough to reject the null hypothesis.</p>
<p>A test turns the sample data into a single number, a <strong>test statistic</strong>, that measures how far the data sit from what the null hypothesis predicts under the sampling distribution. R then converts that statistic into a <strong>p-value</strong>: the probability of seeing that test statistic at least this extreme, if the null hypothesis were actually true. A p-value is not the probability that the null hypothesis is true, and it’s not the probability the result happened by chance. A small p-value, conventionally below 0.05, means the data would be unusual under the null hypothesis, so we reject it in favour of the alternative. A p-value alone says nothing about how large an effect is, only about how surprising it is.</p>
<p>A confidence interval and a hypothesis test carry the same information, read two different ways. If a 95% confidence interval for a difference excludes the null value, 0 for a difference, 1 for a risk ratio or odds ratio, the matching test rejects the null hypothesis at the 5% level, and vice versa. That’s why Chapter 4 could already show us a real effect using intervals alone, before this chapter ever named a null hypothesis. From here on, every test in this book states its null and alternative hypothesis in words before running the test, always as a statement about the population, never about the sample or the particular study, and every result is reported the way the seminar set out: an effect size, a confidence interval, and a p-value, together.</p>
</section>
<section id="one-sample-t-test-total-cholesterol-against-a-clinical-benchmark" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="one-sample-t-test-total-cholesterol-against-a-clinical-benchmark"><span class="header-section-number">5.4</span> One-sample t-test: total cholesterol against a clinical benchmark</h2>
<p>Guideline bodies often set a single reference value for a measurement: a ‘desirable’ total cholesterol of under 5.2 mmol/L is a standard clinical benchmark. A one-sample t-test asks whether the population’s mean differs from a single fixed value like that one, instead of from another group’s mean.</p>
<p><strong>Null hypothesis.</strong> Mean total cholesterol in the population is 5.2 mmol/L.</p>
<p><strong>Alternative hypothesis.</strong> Mean total cholesterol in the population is not 5.2 mmol/L.</p>
<p><code>t.test()</code> runs a one-sample test when we give it one variable and a value to test it against, <code>mu</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(nhanes<span class="sc">$</span>chol, <span class="at">mu =</span> <span class="fl">5.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  nhanes$chol
t = -41.12, df = 39175, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 5.2
95 percent confidence interval:
 4.962511 4.984121
sample estimates:
mean of x 
 4.973316 </code></pre>
</div>
</div>
<p>R prints a 95% confidence interval for the mean itself, 4.96 to 4.98 mmol/L, not for the quantity the test is actually about, which is how far that mean sits from the 5.2 mmol/L benchmark. Subtracting 5.2 from both ends turns it into the effect size we want: mean total cholesterol in this sample is about 4.97 mmol/L, 0.23 mmol/L below the 5.2 mmol/L benchmark (95% CI: 0.22 to 0.24 mmol/L below, p &lt; 0.001). This is the same move the independent-samples section further on makes with its own confidence interval: read what R printed, then work out what it means for the comparison actually being asked.</p>
<p>A one-sample t-test assumes the <strong>sampling distribution</strong> of the mean is roughly normally distributed, not that <code>chol</code> itself is. We never see a sampling distribution directly, since we only have the one sample, so the shape of the data is the evidence we have about it. The central limit theorem says the sampling distribution of the mean gets closer to normal as the sample grows, whatever shape the data themselves have, and the more skewed the data, the larger a sample that takes. Chapter 3’s histogram of <code>chol</code> showed a distribution with a mild right skew, not a perfectly symmetric bell shape, but with a sample this large, tens of thousands of participants, that skew is easily large enough for the theorem to apply. So the question a histogram answers here is not ‘is <code>chol</code> normal?’ but ‘is this sample large enough, given how skewed <code>chol</code> is?’, and for <code>chol</code> the answer is a comfortable yes. <code>wilcox.test()</code> is the non-parametric alternative, for a smaller sample (typically &lt;30) or a more pronounced skew where that reassurance is less safe.</p>
<p><strong>Null hypothesis (<code>wilcox.test()</code>).</strong> The population median of <code>chol</code> is 5.2 mmol/L.</p>
<p><strong>Alternative hypothesis.</strong> The population median is not 5.2 mmol/L.</p>
<p><code>wilcox.test()</code>, from base R, takes the same <code>mu</code> argument for a one-sample test. Rather than a mean, it tests a <strong>median</strong>, using the ranks of how far each value sits from <code>mu</code>, so one extreme value can’t dominate the result the way it can dominate a mean:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(nhanes<span class="sc">$</span>chol, <span class="at">mu =</span> <span class="fl">5.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  nhanes$chol
V = 268972135, p-value &lt; 2.2e-16
alternative hypothesis: true location is not equal to 5.2</code></pre>
</div>
</div>
<p><code>wilcox.test()</code> returns a p-value and nothing else, no effect size, so the size of the effect has to come from a descriptive statistic that matches what the test is about: a median, not a mean. The sample median of <code>chol</code> is 4.89 mmol/L (IQR: 4.22 to 5.61 mmol/L), below the 5.2 mmol/L benchmark, consistent with the p-value far below 0.001. Typical cholesterol in this sample sits below the clinical benchmark whichever way we measure the middle of the distribution. With a sample this large, a t-test and its non-parametric alternative usually agree, but we should stay alert for when the central limit theorem’s reassurance runs thin, in a smaller sample or a more skewed one.</p>
</section>
<section id="paired-t-test-two-domains-of-activity-in-one-person" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="paired-t-test-two-domains-of-activity-in-one-person"><span class="header-section-number">5.5</span> Paired t-test: two domains of activity in one person</h2>
<p><code>nhanes_mph</code> records physical activity as two separate totals for each participant, both in MET-hours/day: <code>met_w</code>, activity at work, and <code>met_r</code>, activity outside work, exactly as the dictionary describes it. These are two different domains of activity, measured at the same time, in the same person.</p>
<p>That distinction decides which test applies. The one-sample test above compared one variable against a fixed value. Here there’s no fixed value: two measurements to compare, both taken on the same people. That’s not the same as comparing two separate groups, an independent-samples test, introduced later in this chapter. Every <code>met_w</code> value here has exactly one matching <code>met_r</code> value, from the same participant. The right tool is a paired t-test. Instead of comparing the two columns directly, it collapses them into a single column of within-person differences (<code>met_w</code> minus <code>met_r</code>) and tests whether that difference is, on average, zero.</p>
<p><strong>Null hypothesis.</strong> In the population, mean work activity and mean outside-work activity are the same: the mean within-person difference is zero.</p>
<p><strong>Alternative hypothesis.</strong> The mean within-person difference is not zero.</p>
<p><code>t.test()</code> runs a paired test when we set <code>paired = TRUE</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(nhanes<span class="sc">$</span>met_w, nhanes<span class="sc">$</span>met_r, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  nhanes$met_w and nhanes$met_r
t = 43.111, df = 34284, p-value &lt; 2.2e-16
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 2.927984 3.206905
sample estimates:
mean difference 
       3.067444 </code></pre>
</div>
</div>
<p>On average, work activity ran about 3.07 MET-hours/day higher than activity outside work (95% CI: 2.93 to 3.21 MET-hours/day, p &lt; 0.001).</p>
<p>A paired t-test also arises in a before-and-after design, where the same measurement is taken at two time points on the same person. That is a different study design from the one here, even though the R code looks identical. There is no repeated measurement over time in this data, and describing the result as though there were would plant a habit that causes real trouble in a longitudinal design later on.</p>
<p>We can also get the paired t-test result by running an ordinary one-sample t-test on the differences directly, testing whether <code>met_w - met_r</code> has a mean of zero, exactly the calculation the one-sample section above just introduced:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(nhanes<span class="sc">$</span>met_w <span class="sc">-</span> nhanes<span class="sc">$</span>met_r)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  nhanes$met_w - nhanes$met_r
t = 43.111, df = 34284, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 0
95 percent confidence interval:
 2.927984 3.206905
sample estimates:
mean of x 
 3.067444 </code></pre>
</div>
</div>
<p>The t-statistic, degrees of freedom, and p-value are identical to the paired test above. That’s not a coincidence: <code>paired = TRUE</code> is doing exactly this calculation internally, collapsing the two columns into one column of differences first.</p>
</section>
<section id="a-non-parametric-alternative-the-wilcoxon-signed-rank-test" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="a-non-parametric-alternative-the-wilcoxon-signed-rank-test"><span class="header-section-number">5.6</span> A non-parametric alternative: the Wilcoxon signed-rank test</h2>
<p>A paired t-test assumes the sampling distribution of the within-person difference is at least roughly normally distributed, the same kind of claim the one-sample section above explained. Let’s look at the data’s distribution, this time with a histogram, since the within-person difference is a new variable we haven’t looked at yet:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes <span class="sc">|&gt;</span> <span class="fu">mutate</span>(<span class="at">met_diff =</span> met_w <span class="sc">-</span> met_r), <span class="fu">aes</span>(<span class="at">x =</span> met_diff)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Work minus outside-work activity (MET-hours/day)'</span>, <span class="at">y =</span> <span class="st">'Count'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7480 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-comparison_files/figure-html/hist-met-diff-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The distribution of differences is heavily skewed, and a large share of participants sit exactly at zero. Many people report no occupational activity at all, so <code>met_w</code> and <code>met_r</code> are equal for them. The paired t-test may still be fine, because the sample size is large enough for the central limit theorem to apply, but a skew this pronounced is a good reason to check the conclusion against a test that doesn’t lean on that theorem at all.</p>
<p><code>wilcox.test()</code> also tests the same question as the paired t-test here, without assuming a normal distribution. It works with the ranks of the differences rather than their average, so one extreme value or an oddly-shaped distribution can’t dominate the result the way it can dominate a mean.</p>
<p><strong>Null hypothesis.</strong> In the population, work activity and outside-work activity are equally likely to be the larger of the pair: there’s no systematic difference within the pair.</p>
<p><strong>Alternative hypothesis.</strong> One is systematically larger than the other.</p>
<p>With <code>paired = TRUE</code>, it runs the paired version, known as the Wilcoxon signed-rank test:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(nhanes<span class="sc">$</span>met_w, nhanes<span class="sc">$</span>met_r, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  nhanes$met_w and nhanes$met_r
V = 169408552, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>The conclusion doesn’t change here: both tests reject the null hypothesis convincingly, each with a p-value far below 0.001, and the paired t-test’s own effect size above, work activity running about 3.07 MET-hours/day higher, still stands as the effect-size figure to report alongside either p-value. With a sample this large, the t-test and the Wilcoxon test agree despite the skew. That won’t always be true. With a smaller sample, or a more extreme distribution, the two tests can disagree, and the non-parametric result is usually the one to trust when the normality assumption is in real doubt.</p>
</section>
<section id="independent-samples-t-test-cholesterol-by-gender" class="level2" data-number="5.7">
<h2 data-number="5.7" class="anchored" data-anchor-id="independent-samples-t-test-cholesterol-by-gender"><span class="header-section-number">5.7</span> Independent-samples t-test: cholesterol by gender</h2>
<p>Unlike the paired comparison just above, an independent-samples t-test compares two entirely separate groups of people, with no link between a value in one group and a value in the other. <code>t.test()</code> compares two independent groups directly. We already used it in Chapter 4 to build a confidence interval for the difference in total cholesterol (<code>chol</code>, in mmol/L) between men and women.</p>
<p><strong>Null hypothesis.</strong> Mean total cholesterol is the same in men and women in the population.</p>
<p><strong>Alternative hypothesis.</strong> Mean total cholesterol differs between men and women in the population.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(chol <span class="sc">~</span> gender, <span class="at">data =</span> nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  chol by gender
t = -15.318, df = 38908, p-value &lt; 2.2e-16
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -0.1901172 -0.1469821
sample estimates:
  mean in group Male mean in group Female 
            4.885939             5.054489 </code></pre>
</div>
</div>
<p>This is the exact same call as Chapter 4’s. <code>t.test()</code> was already giving us a hypothesis test; Chapter 4 just hadn’t introduced hypothesis testing yet, so we only looked at the confidence interval. Now we bring the rest into view: a t-statistic, degrees of freedom, and a p-value.</p>
<p>Before trusting a t-test, we check that the two groups aren’t wildly different in spread or shape, the way Chapter 3’s boxplot of <code>chol</code> by <code>gender</code> already let us do. This is a different check from the sampling-distribution question the one-sample and paired sections asked: there, the concern was whether one sampling distribution was close to normal; here, with two separate groups, the concern is whether the two groups look comparable enough in spread and shape for a difference in their means to be meaningful.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)), <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> chol)) <span class="sc">+</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Gender'</span>, <span class="at">y =</span> <span class="st">'Total cholesterol (mmol/L)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2589 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-comparison_files/figure-html/boxplot-recheck-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The two boxplots are similar in spread and shape, just shifted slightly. Nothing here rules out a t-test. If, instead, the shape of the boxplot looks very different between the two groups, a t-test might not be appropriate, since it only compares the sample means. <code>t.test()</code> also doesn’t assume equal variance between the two groups by default, which protects us even where the spreads differ more than they do here.</p>
<p>Before reading the interval, check the direction, exactly as Chapter 4 set out. The alternative-hypothesis line says <em>group Male and group Female</em>, because <code>'Male'</code> is the first level of <code>gender</code>, so R has printed men minus women and both ends come out negative. Reversing every sign together turns it into the more natural reading: mean total cholesterol was about 0.17 mmol/L higher in women than in men (95% CI: 0.15 to 0.19 mmol/L, p &lt; 0.001). The two statements are the same result written from a different perspective. This is the reporting standard the seminar introduced: effect size, confidence interval, and p-value, together, every time, from here on. <code>p &lt; 0.001</code> is how we write a p-value that R prints as something like <code>&lt; 2.2e-16</code>. Convention in public health (or clinical medicine) reports a very small p-value this way rather than typing out the scientific notation.</p>
</section>
<section id="chi-squared-test-strep_tbs-primary-result" class="level2" data-number="5.8">
<h2 data-number="5.8" class="anchored" data-anchor-id="chi-squared-test-strep_tbs-primary-result"><span class="header-section-number">5.8</span> Chi-squared test: <code>strep_tb</code>’s primary result</h2>
<p><code>strep_tb</code>’s primary outcome is binary: did chest X-ray improve at six months (<code>improved</code>), and does that depend on trial arm (<code>arm</code>)? <code>table()</code> builds a two-way count, the same way it did in Chapter 3, and <code>chisq.test()</code>, from base R, tests whether the two variables are associated.</p>
<p><strong>Null hypothesis.</strong> The probability of improvement is the same in the population of patients receiving streptomycin and the population of patients receiving control treatment.</p>
<p><strong>Alternative hypothesis.</strong> The probability of improvement is not the same in the two populations.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>tab_arm <span class="ot">&lt;-</span> <span class="fu">table</span>(strep_tb<span class="sc">$</span>arm, strep_tb<span class="sc">$</span>improved)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>tab_arm</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              
               FALSE TRUE
  Streptomycin    17   38
  Control         35   17</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab_arm, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab_arm
X-squared = 14.176, df = 1, p-value = 0.0001665</code></pre>
</div>
</div>
<p>The chi-squared statistic is large and the p-value is small: the proportion improved is not the same in the two arms. A p-value alone doesn’t say by how much; the risk ratio and odds ratio below put a size on that difference.</p>
<p>A chi-squared test also has an assumption to check. Every <strong>expected</strong> count should be reasonably large, conventionally at least 5. <code>chisq.test()</code> calculates these expected counts internally and stores them in <code>$expected</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab_arm, <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              
                  FALSE     TRUE
  Streptomycin 26.72897 28.27103
  Control      25.27103 26.72897</code></pre>
</div>
</div>
<p>All four expected counts are comfortably above 5, so the test is on solid ground here. Expected counts run low typically in a small or very unevenly split sample. When that happens, <code>fisher.test()</code>, also from base R, is the alternative: it tests the same association exactly, rather than by approximation, and doesn’t depend on that condition.</p>
<p><code>correct = FALSE</code> switches off a specific adjustment. Left alone on a 2×2 table, <code>chisq.test()</code> applies <strong>Yates’ continuity correction</strong> by default: it subtracts 0.5 from the absolute difference between each observed and expected count before squaring, a conservative adjustment that compensates for approximating whole-number counts with a smooth curve. It shrinks the test statistic slightly, so it makes the p-value larger.</p>
<p>We’ve already met it without being told what it was. Chapter 4’s <code>prop.test()</code> on these same two arms was headed ‘with continuity correction’ too, and printed a p-value of 0.0003548. The uncorrected test above gives 0.000166: same data, same comparison, two different numbers, purely from this one default.</p>
<p>The correction earns its place when expected counts run low, typically down around 5 to 10. Ours aren’t: the smallest expected count is above 25. So we switch it off here, and it’s also what makes this p-value match the one <code>epitools</code> reports for the same table in the next section.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Try it yourself: two tests, one answer
</div>
</div>
<div class="callout-body-container callout-body">
<p>Chapter 4’s <code>prop.test()</code> compares two proportions; this section’s <code>chisq.test()</code> tests association in a two-way table. Run <code>prop.test(tab_arm, correct = FALSE)</code> and compare its chi-squared statistic and p-value to <code>chisq.test(tab_arm, correct = FALSE)</code> above, digit for digit. Write one sentence on what that match tells us about how the two tests relate, for a 2×2 table like this one.</p>
<p><code>prop.test()</code> also prints something <code>chisq.test()</code> doesn’t: a confidence interval for the difference between the two proportions. Read the two proportions R prints and check which category of <code>improved</code> they refer to, the same way Chapter 4 warned to check before feeding a table straight in. Reverse the signs if needed, the way the independent-samples section above reversed its own interval, and write a one-sentence results statement giving the risk difference between the two arms with its 95% confidence interval. Write a second sentence on why that statement is something <code>chisq.test()</code> alone could never have given us.</p>
</div>
</div>
</section>
<section id="fishers-exact-test" class="level2" data-number="5.9">
<h2 data-number="5.9" class="anchored" data-anchor-id="fishers-exact-test"><span class="header-section-number">5.9</span> Fisher’s exact test</h2>
<p>This is the test to reach for when a chi-squared test’s expected-count assumption fails, which in public health work usually means a small trial or a rare outcome, both common enough that knowing the fix in advance pays off. It tests the same null and alternative hypothesis as the chi-squared test above, independence versus dependence between arm and improvement, just by an exact calculation instead of an approximation. Let’s try <code>fisher.test()</code> on this table too, even though nothing here required it. The call looks just like <code>chisq.test()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fisher.test</span>(tab_arm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Fisher's Exact Test for Count Data

data:  tab_arm
p-value = 0.0002218
alternative hypothesis: true odds ratio is not equal to 1
95 percent confidence interval:
 0.08866883 0.52737127
sample estimates:
odds ratio 
 0.2207311 </code></pre>
</div>
</div>
<p>The p-value, 0.0002218, is close to the chi-squared test’s 0.000166. Both lead to the same conclusion here, a clear association between arm and improvement. <code>riskratio()</code> and <code>oddsratio()</code>, met below, report a Fisher’s exact p-value of their own for the same table, so this number will reappear.</p>
<p>On a larger table, with many categories instead of the 2×2 shape here, <code>fisher.test()</code> can become slow, because it enumerates every possible table with the same row and column totals to work out the exact probability. If it runs too slowly or refuses with an error on a bigger table, adding <code>simulate.p.value = TRUE</code> switches it to a Monte Carlo estimate instead of the exact calculation, trading a small amount of precision for speed. That isn’t needed here.</p>
</section>
<section id="risk-ratios-and-odds-ratios-with-confidence-intervals" class="level2" data-number="5.10">
<h2 data-number="5.10" class="anchored" data-anchor-id="risk-ratios-and-odds-ratios-with-confidence-intervals"><span class="header-section-number">5.10</span> Risk ratios and odds ratios, with confidence intervals</h2>
<p>The epidemiology half already taught how to calculate a risk ratio and an odds ratio from a 2×2 table like <code>tab_arm</code> above, and what each one means. We don’t re-derive those formulas here. What’s new is attaching a confidence interval and a p-value to numbers we can already compute by hand, and checking that R’s version agrees with ours.</p>
<p><code>riskratio()</code> and <code>oddsratio()</code>, both from <code>epitools</code>, take a 2×2 table and compare its rows, treating the first row as the reference category everything else is measured against.</p>
<p><strong>Null hypothesis.</strong> In the population, the risk ratio is 1, and the odds ratio is 1: no association between arm and improvement.</p>
<p><strong>Alternative hypothesis.</strong> The risk ratio, and the odds ratio, differ from 1.</p>
<p>Note the null value sits at 1 for a risk ratio or an odds ratio, not 0. A ratio of 1 means the two groups’ risk, or odds, are identical; a difference in means or a slope has its null at 0 instead, because there the null value means no gap rather than no ratio.</p>
<p>They expect the table a particular way round, and getting it wrong produces a perfectly ordinary-looking answer, not an error, so check the layout before building one. The <strong>exposure goes in the rows</strong>, with the reference group first. The <strong>outcome goes in the columns</strong>, and the second column is taken as the event: the thing whose risk we’re comparing. Our table has <code>arm</code> in the rows and <code>improved</code> in the columns. <code>improved</code> holds <code>TRUE</code>/<code>FALSE</code> values, and <code>table()</code> orders these <code>FALSE</code> then <code>TRUE</code>, so improvement lands in the second column exactly as needed. Print the table and look at it before passing it on. If the reference row or the event column is the wrong one, these functions still return a risk ratio, just an upside-down one.</p>
<p><code>levels()</code>, from base R, lists a factor’s categories in their current order, which is what we need to check before comparing rows:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(strep_tb<span class="sc">$</span>arm)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Streptomycin" "Control"     </code></pre>
</div>
</div>
<p><code>Streptomycin</code> is listed first, which would make it the reference, backwards from what we want here. <code>relevel()</code>, met in Chapter 3, moves the level named in <code>ref</code> to the front, making it the new reference level. There we were only demonstrating it; here it changes the answer:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>arm_control_ref <span class="ot">&lt;-</span> <span class="fu">relevel</span>(strep_tb<span class="sc">$</span>arm, <span class="at">ref =</span> <span class="st">'Control'</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(arm_control_ref)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Control"      "Streptomycin"</code></pre>
</div>
</div>
<p><code>Control</code> is now first, so it becomes the reference row: the one everything else is compared against. This is the same reference level idea we met with factors in Chapter 3, now doing real work instead of being demonstrated on a copy. Using it here, a second time before Chapter 6, is good practice: setting a sensible reference level is part of fitting a regression model there too.</p>
<p>We rebuild the table with the releveled factor, and pass it to <code>riskratio()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>tab_arm_releveled <span class="ot">&lt;-</span> <span class="fu">table</span>(arm_control_ref, strep_tb<span class="sc">$</span>improved)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>tab_arm_releveled</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               
arm_control_ref FALSE TRUE
   Control         35   17
   Streptomycin    17   38</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(tab_arm_releveled)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
               
arm_control_ref FALSE TRUE Total
   Control         35   17    52
   Streptomycin    17   38    55
   Total           52   55   107

$measure
               risk ratio with 95% C.I.
arm_control_ref estimate    lower    upper
   Control      1.000000       NA       NA
   Streptomycin 2.113369 1.377267 3.242893

$p.value
               two-sided
arm_control_ref   midp.exact fisher.exact  chi.square
   Control                NA           NA          NA
   Streptomycin 0.0001868959 0.0002217708 0.000166482

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
</div>
<p><code>oddsratio()</code> works the same way. We ask for <code>method = 'wald'</code>, which uses the same normal-approximation logic behind the ± 1.96 × SE intervals from Chapter 4. This matches the simple cross-product formula from the hand calculation directly:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(tab_arm_releveled, <span class="at">method =</span> <span class="st">'wald'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
               
arm_control_ref FALSE TRUE Total
   Control         35   17    52
   Streptomycin    17   38    55
   Total           52   55   107

$measure
               odds ratio with 95% C.I.
arm_control_ref estimate    lower   upper
   Control      1.000000       NA      NA
   Streptomycin 4.602076 2.038863 10.3877

$p.value
               two-sided
arm_control_ref   midp.exact fisher.exact  chi.square
   Control                NA           NA          NA
   Streptomycin 0.0001868959 0.0002217708 0.000166482

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
</div>
<p>From the table above: 38 of 55 patients improved in the streptomycin arm (risk = 0.69), and 17 of 52 improved in the control arm (risk = 0.33). By hand, risk ratio = 0.69 / 0.33 = 2.11, and odds ratio = (38 × 35) / (17 × 17) = 4.60. Both match what <code>riskratio()</code> and <code>oddsratio()</code> just reported, with a confidence interval attached to each: a risk ratio of 2.11 (95% CI: 1.38 to 3.24) and an odds ratio of 4.60 (95% CI: 2.04 to 10.39). Neither interval comes close to including 1, the null value for both a risk ratio and an odds ratio, consistent with the chi-squared test above.</p>
<p><code>riskratio()</code> and <code>oddsratio()</code> each also report three p-values alongside the estimate: a mid-p exact test, Fisher’s exact test, and a chi-squared test. All three agree closely here. The chi-squared one is 0.000166, exactly the p-value <code>chisq.test(tab_arm, correct = FALSE)</code> gave us above, to every digit printed. That’s only because we switched the continuity correction off. Had we left the correction on, <code>chisq.test()</code> would have reported 0.0003548, the number Chapter 4’s <code>prop.test()</code> printed, while <code>epitools</code> reported 0.000166. There’d be no way to tell from the output that the two functions had simply made different default choices.</p>
</section>
<section id="gtsummarytbl_summary-with-a-test-attached" class="level2" data-number="5.11">
<h2 data-number="5.11" class="anchored" data-anchor-id="gtsummarytbl_summary-with-a-test-attached"><span class="header-section-number">5.11</span> <code>gtsummary::tbl_summary()</code> with a test attached</h2>
<p><code>tbl_summary()</code>, already met in Chapter 3, can attach a test to a stratified table with <code>add_p()</code>, piped on afterwards:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>strep_tb <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(arm, improved) <span class="sc">|&gt;</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tbl_summary</span>(<span class="at">by =</span> arm) <span class="sc">|&gt;</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_p</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-summary-addp" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl quarto-uncaptioned" id="tbl-summary-addp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5.1
</figcaption>
<div aria-describedby="tbl-summary-addp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div id="ysnyndyhwn" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ysnyndyhwn table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ysnyndyhwn thead, #ysnyndyhwn tbody, #ysnyndyhwn tfoot, #ysnyndyhwn tr, #ysnyndyhwn td, #ysnyndyhwn th {
  border-style: none;
}

#ysnyndyhwn p {
  margin: 0;
  padding: 0;
}

#ysnyndyhwn .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ysnyndyhwn .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ysnyndyhwn .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ysnyndyhwn .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ysnyndyhwn .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ysnyndyhwn .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ysnyndyhwn .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ysnyndyhwn .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ysnyndyhwn .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ysnyndyhwn .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ysnyndyhwn .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ysnyndyhwn .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ysnyndyhwn .gt_spanner_row {
  border-bottom-style: hidden;
}

#ysnyndyhwn .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ysnyndyhwn .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ysnyndyhwn .gt_from_md > :first-child {
  margin-top: 0;
}

#ysnyndyhwn .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ysnyndyhwn .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ysnyndyhwn .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ysnyndyhwn .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ysnyndyhwn .gt_row_group_first td {
  border-top-width: 2px;
}

#ysnyndyhwn .gt_row_group_first th {
  border-top-width: 2px;
}

#ysnyndyhwn .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ysnyndyhwn .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ysnyndyhwn .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ysnyndyhwn .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ysnyndyhwn .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ysnyndyhwn .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ysnyndyhwn .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ysnyndyhwn .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ysnyndyhwn .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ysnyndyhwn .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ysnyndyhwn .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ysnyndyhwn .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ysnyndyhwn .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ysnyndyhwn .gt_left {
  text-align: left;
}

#ysnyndyhwn .gt_center {
  text-align: center;
}

#ysnyndyhwn .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ysnyndyhwn .gt_font_normal {
  font-weight: normal;
}

#ysnyndyhwn .gt_font_bold {
  font-weight: bold;
}

#ysnyndyhwn .gt_font_italic {
  font-style: italic;
}

#ysnyndyhwn .gt_super {
  font-size: 65%;
}

#ysnyndyhwn .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ysnyndyhwn .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ysnyndyhwn .gt_indent_1 {
  text-indent: 5px;
}

#ysnyndyhwn .gt_indent_2 {
  text-indent: 10px;
}

#ysnyndyhwn .gt_indent_3 {
  text-indent: 15px;
}

#ysnyndyhwn .gt_indent_4 {
  text-indent: 20px;
}

#ysnyndyhwn .gt_indent_5 {
  text-indent: 25px;
}

#ysnyndyhwn .katex-display {
  display: inline-flex !important;
  margin-bottom: 0.75em !important;
}

#ysnyndyhwn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {
  height: 0px !important;
}
</style>

<table class="gt_table do-not-create-environment caption-top table table-sm table-striped small" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="gt_col_headings header">
<th id="label" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col"><strong>Characteristic</strong></th>
<th id="stat_1" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Streptomycin</strong><br>
N = 55<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="stat_2" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>Control</strong><br>
N = 52<span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span></th>
<th id="p.value" class="gt_col_heading gt_columns_bottom_border gt_center" data-quarto-table-cell-role="th" scope="col"><strong>p-value</strong><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span></th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="label">improved</td>
<td class="gt_row gt_center" headers="stat_1">38 (69%)</td>
<td class="gt_row gt_center" headers="stat_2">17 (33%)</td>
<td class="gt_row gt_center" headers="p.value">&lt;0.001</td>
</tr>
</tbody><tfoot>
<tr class="gt_footnotes odd">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>1</sup></span> n (%)</td>
</tr>
<tr class="gt_footnotes even">
<td colspan="4" class="gt_footnote"><span class="gt_footnote_marks" style="white-space:nowrap;font-style:italic;font-weight:normal;line-height:0;"><sup>2</sup></span> Pearson’s Chi-squared test</td>
</tr>
</tfoot>

</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>This single call reproduces the count, the percentage, and the p-value we built by hand above, in the one-line form we’ll reach for once the manual steps are familiar. The p-value matches to every digit because <code>add_p()</code> happens to default to the <em>uncorrected</em> chi-squared test here, the same choice we made by hand with <code>correct = FALSE</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Try it yourself: sample size and significance
</div>
</div>
<div class="callout-body-container callout-body">
<p>Using <code>slice_sample()</code> from Chapter 4, take a 10% random subsample of <code>nhanes</code> (remember to <code>set.seed()</code> first, so the subsample is reproducible) and re-run the <code>chol ~ gender</code> t-test from earlier in this chapter on it. Compare the p-value and the confidence interval to the ones from the full sample. Note what changed in one sentence, then explain in a second what it means for judging whether a small p-value reflects a large effect or simply a large sample.</p>
</div>
</div>
</section>
<section id="worked-example-sedentary-time-by-gender" class="level2" data-number="5.12">
<h2 data-number="5.12" class="anchored" data-anchor-id="worked-example-sedentary-time-by-gender"><span class="header-section-number">5.12</span> Worked example: sedentary time by gender</h2>
<p>Let’s bring the independent-samples t-test together on a research question we haven’t asked elsewhere in this chapter: does sedentary time (<code>sed</code>, in hours/day) differ between men and women?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)), <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> sed)) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Gender'</span>, <span class="at">y =</span> <span class="st">'Sedentary time (hours/day)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 7331 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-comparison_files/figure-html/worked-boxplot-sed-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sed <span class="sc">~</span> gender, <span class="at">data =</span> nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sed by gender
t = -2.2193, df = 33827, p-value = 0.02648
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 -0.48830744 -0.03028725
sample estimates:
  mean in group Male mean in group Female 
            6.430592             6.689889 </code></pre>
</div>
</div>
<p>The boxplots overlap substantially, with similar spread in each group, so a t-test is reasonable here too. R prints the difference men minus women once again, so the interval on the page runs from -0.49 to -0.03. Put into a sentence, with the whole thing reversed: women reported slightly more sedentary time than men (mean difference about 0.26 hours/day, 95% CI: 0.03 to 0.49 hours/day, p = 0.026). The interval doesn’t include zero, so the difference is statistically significant, but it’s a small effect, about 15 minutes a day, on a scale of many hours a day.</p>
</section>
<section id="exercises" class="level2" data-number="5.13">
<h2 data-number="5.13" class="anchored" data-anchor-id="exercises"><span class="header-section-number">5.13</span> Exercises</h2>
<p><strong>Exercise 1</strong> (ILOs 1, 3). State the null and alternative hypotheses for a one-sample test of sedentary time (<code>sed</code>) against a reference value of 6 hours/day. Perform a one-sample t-test with <code>t.test()</code>, then repeat it with <code>wilcox.test()</code>. Report both results in one sentence each, each with its own effect size, and write a third sentence on why the mean and the median of <code>sed</code> might point to different conclusions about a typical participant’s sedentary time.</p>
<p><strong>Exercise 2</strong> (ILOs 1, 3). State the null and alternative hypotheses for a paired comparison of <code>met_w</code> and <code>met_r</code>. Using <code>filter()</code>, restrict <code>nhanes</code> to participants whose sedentary time (<code>sed</code>) is above the sample median. On this subgroup, run both a paired t-test and a Wilcoxon signed-rank test comparing <code>met_w</code> and <code>met_r</code>. Write one sentence stating whether your conclusion changes in this more sedentary subgroup, and one sentence explaining why <code>met_w</code> and <code>met_r</code> are still a paired comparison here, not an independent one, even after filtering.</p>
<p><strong>Exercise 3</strong> (ILO 1). State the null and alternative hypotheses, then perform an independent-samples t-test comparing age (<code>age</code>) between men and women. Check the assumption graphically first with a boxplot. Report the result in a single sentence, and add one more sentence on whether a statistically significant result here is also a practically important one.</p>
<p><strong>Exercise 4</strong> (ILOs 2, 3). State the null and alternative hypotheses, then construct a contingency table of baseline cavitation (<code>baseline_cavitation</code>) against improvement (<code>improved</code>) in <code>strep_tb</code>. Run a chi-squared test, check the expected counts, and write one sentence interpreting the result.</p>
<p><strong>Exercise 5</strong> (ILOs 4, 5). State the null and alternative hypotheses for the risk ratio and the odds ratio, noting the scale their null value sits on. Using the same method as the <code>arm</code>/<code>improved</code> example above, check with <code>levels()</code> which category of <code>gender</code> is already the reference, then use <code>relevel()</code> to set it explicitly (even if it turns out to already be the one you want). Obtain a risk ratio and an odds ratio, each with a 95% confidence interval, for improvement in men compared with women. Reconcile the software output with a hand calculation from the same 2×2 table, and write a two-sentence results statement.</p>
</section>
<section id="writing-exercise" class="level2" data-number="5.14">
<h2 data-number="5.14" class="anchored" data-anchor-id="writing-exercise"><span class="header-section-number">5.14</span> Writing exercise</h2>
<p>Using the <code>arm</code>/<code>improved</code> result from earlier in this chapter, write two sentences for <code>strep_tb</code>’s primary outcome. State the proportion improved in each arm, and report the risk ratio or the odds ratio (your choice), its 95% confidence interval, and its p-value, together.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Solutions
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Exercise 1</strong></p>
<p><strong>Null hypothesis.</strong> In the population, mean sedentary time is 6 hours/day (t-test); median sedentary time is 6 hours/day (<code>wilcox.test()</code>).</p>
<p><strong>Alternative hypothesis.</strong> The mean, or the median, is not 6 hours/day.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(nhanes<span class="sc">$</span>sed, <span class="at">mu =</span> <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  nhanes$sed
t = 9.6046, df = 34433, p-value &lt; 2.2e-16
alternative hypothesis: true mean is not equal to 6
95 percent confidence interval:
 6.449124 6.679429
sample estimates:
mean of x 
 6.564277 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(nhanes<span class="sc">$</span>sed, <span class="at">mu =</span> <span class="dv">6</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  nhanes$sed
V = 216498063, p-value &lt; 2.2e-16
alternative hypothesis: true location is not equal to 6</code></pre>
</div>
</div>
<p>R’s confidence interval, 6.45 to 6.68 hours/day, is for the mean itself; subtracting the 6-hour benchmark from both ends gives the effect size: mean sedentary time is about 6.56 hours/day, 0.56 hours/day above 6 hours/day (95% CI: 0.45 to 0.68 hours/day above, p &lt; 0.001). The Wilcoxon test is significant too (p &lt; 0.001), but it’s testing a different quantity, so its effect size is a median, not a mean: sample median 5 hours/day (IQR: 3 to 8 hours/day), <em>below</em> the 6-hour benchmark. The mean and the median disagree on which side of 6 hours ‘typical’ sedentary time falls. Sedentary time is right-skewed: a small number of participants report very high values, which pulls the mean up above the median, and above the benchmark, while the middle of the distribution, where most participants actually sit, remains below it. A typical participant, in the middle of the distribution, reports noticeably less sedentary time than the mean alone would suggest.</p>
<p><strong>Exercise 2</strong></p>
<p><strong>Null hypothesis.</strong> In the population of participants in this more sedentary subgroup, the mean within-person difference between <code>met_w</code> and <code>met_r</code> is zero.</p>
<p><strong>Alternative hypothesis.</strong> The mean within-person difference is not zero.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>sed_above_median <span class="ot">&lt;-</span> nhanes <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(sed), sed <span class="sc">&gt;</span> <span class="fu">median</span>(sed, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sed_above_median<span class="sc">$</span>met_w, sed_above_median<span class="sc">$</span>met_r, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  sed_above_median$met_w and sed_above_median$met_r
t = 7.4471, df = 16724, p-value = 1e-13
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 0.3593059 0.6160133
sample estimates:
mean difference 
      0.4876596 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(sed_above_median<span class="sc">$</span>met_w, sed_above_median<span class="sc">$</span>met_r, <span class="at">paired =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon signed rank test with continuity correction

data:  sed_above_median$met_w and sed_above_median$met_r
V = 25597758, p-value &lt; 2.2e-16
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Both tests still reject the null hypothesis in this more sedentary subgroup, though the mean difference is much smaller than in the whole sample (about 0.49 MET-hours/day here, versus about 3.07 MET-hours/day overall). <code>met_w</code> and <code>met_r</code> remain two measurements taken on the same person at the same time, so the comparison is paired regardless of filtering.</p>
<p><strong>Exercise 3</strong></p>
<p><strong>Null hypothesis.</strong> Mean age is the same in men and women in the population.</p>
<p><strong>Alternative hypothesis.</strong> Mean age differs between men and women in the population.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)), <span class="fu">aes</span>(<span class="at">x =</span> gender, <span class="at">y =</span> age)) <span class="sc">+</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">'Gender'</span>, <span class="at">y =</span> <span class="st">'Age (years)'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="09-comparison_files/figure-html/sol-ex3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(age <span class="sc">~</span> gender, <span class="at">data =</span> nhanes <span class="sc">|&gt;</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(gender)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  age by gender
t = 4.0035, df = 41503, p-value = 6.251e-05
alternative hypothesis: true difference in means between group Male and group Female is not equal to 0
95 percent confidence interval:
 0.3702765 1.0805737
sample estimates:
  mean in group Male mean in group Female 
            47.89355             47.16813 </code></pre>
</div>
</div>
<p>This time R’s interval is already positive, and that’s informative: the difference is still men minus women, so a positive interval means the first group is the higher one. Men in this sample were on average about 0.7 years older than women (95% CI: 0.4 to 1.1 years, p &lt; 0.001), and no signs need reversing to say so. The difference is statistically significant but tiny relative to a population averaging around 47 years old. With a sample this large, tens of thousands of participants, even a very small true difference will produce a small p-value. Statistical significance here is not the same as a practically important difference, and it doesn’t really contradict Chapter 3’s impression that age looked similar across the two groups.</p>
<p><strong>Exercise 4</strong></p>
<p><strong>Null hypothesis.</strong> In the population, improvement is not associated with baseline cavitation.</p>
<p><strong>Alternative hypothesis.</strong> Improvement depends on baseline cavitation.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>tab_cavitation <span class="ot">&lt;-</span> <span class="fu">table</span>(strep_tb<span class="sc">$</span>baseline_cavitation, strep_tb<span class="sc">$</span>improved)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>tab_cavitation</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
      FALSE TRUE
  no     17   28
  yes    35   27</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab_cavitation, <span class="at">correct =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tab_cavitation
X-squared = 3.6399, df = 1, p-value = 0.05641</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">chisq.test</span>(tab_cavitation, <span class="at">correct =</span> <span class="cn">FALSE</span>)<span class="sc">$</span>expected</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     
         FALSE     TRUE
  no  21.86916 23.13084
  yes 30.13084 31.86916</code></pre>
</div>
</div>
<p>All expected counts are comfortably above 5, the smallest being just under 22, so <code>correct = FALSE</code> is the right call here, for the same reason it was for the <code>arm</code> table.</p>
<p>The chi-squared test gives a p-value of about 0.056. That’s above the conventional 0.05 threshold, but only just, and it would be a mistake to read much into which side of it the number landed on. The honest reading is the same either way: this is weak evidence of an association between baseline cavitation and improvement. The data don’t establish a relationship, but they don’t rule one out either. A trial of 107 patients simply cannot settle a question this size, and the result is best reported as inconclusive.</p>
<p><strong>Exercise 5</strong></p>
<p><strong>Null hypothesis.</strong> In the population, the risk ratio is 1 and the odds ratio is 1: no association between gender and improvement.</p>
<p><strong>Alternative hypothesis.</strong> The risk ratio, and the odds ratio, differ from 1. Both nulls sit at 1, not 0, since these are ratios instead of differences.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(strep_tb<span class="sc">$</span>gender)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "F" "M"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>gender_f_ref <span class="ot">&lt;-</span> <span class="fu">relevel</span>(strep_tb<span class="sc">$</span>gender, <span class="at">ref =</span> <span class="st">'F'</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>tab_gender <span class="ot">&lt;-</span> <span class="fu">table</span>(gender_f_ref, strep_tb<span class="sc">$</span>improved)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>tab_gender</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            
gender_f_ref FALSE TRUE
           F    31   28
           M    21   27</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">riskratio</span>(tab_gender)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
            
gender_f_ref FALSE TRUE Total
       F        31   28    59
       M        21   27    48
       Total    52   55   107

$measure
            risk ratio with 95% C.I.
gender_f_ref estimate     lower    upper
           F 1.000000        NA       NA
           M 1.185268 0.8215655 1.709979

$p.value
            two-sided
gender_f_ref midp.exact fisher.exact chi.square
           F         NA           NA         NA
           M  0.3745488    0.4378977   0.365451

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">oddsratio</span>(tab_gender, <span class="at">method =</span> <span class="st">'wald'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$data
            
gender_f_ref FALSE TRUE Total
       F        31   28    59
       M        21   27    48
       Total    52   55   107

$measure
            odds ratio with 95% C.I.
gender_f_ref estimate     lower    upper
           F 1.000000        NA       NA
           M 1.423469 0.6619167 3.061208

$p.value
            two-sided
gender_f_ref midp.exact fisher.exact chi.square
           F         NA           NA         NA
           M  0.3745488    0.4378977   0.365451

$correction
[1] FALSE

attr(,"method")
[1] "Unconditional MLE &amp; normal approximation (Wald) CI"</code></pre>
</div>
</div>
<p><code>levels()</code> shows that <code>'F'</code> is already listed first, so <code>relevel()</code> here confirms that choice explicitly. By hand, from the table: 27 of 48 men improved (risk = 0.5625) and 28 of 59 women improved (risk = 0.4746), giving a risk ratio of 0.5625 / 0.4746 = 1.19, and an odds ratio of (27 × 31) / (21 × 28) = 1.42. Both match the software output. The proportion improved was slightly higher in men than in women (risk ratio 1.19, 95% CI: 0.82 to 1.71; odds ratio 1.42, 95% CI: 0.66 to 3.06, chi-squared p = 0.37). But both confidence intervals include the null value of 1, so this trial gives no good evidence of a difference in improvement by gender. <code>oddsratio()</code> prints three p-values, as it did for the <code>arm</code> table; the chi-squared one is quoted here because that’s the one that reconciles with <code>chisq.test()</code>.</p>
<p><strong>Writing exercise (sample answer)</strong></p>
<p>Among patients receiving streptomycin, 69% (38 of 55) showed radiological improvement at six months, compared with 33% (17 of 52) among those receiving the control treatment. This corresponds to a risk ratio of 2.11 (95% CI: 1.38 to 3.24, p &lt; 0.001): about twice the proportion improved with streptomycin compared with control in this trial.</p>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../chapters/08-estimation.html" class="pagination-link" aria-label="Estimation, precision, and sample size (Week 8)">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Estimation, precision, and sample size (Week 8)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../chapters/10-regression.html" class="pagination-link" aria-label="Correlation and simple linear regression (Week 10)">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Correlation and simple linear regression (Week 10)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>